### ISSUE TITLE
pls check this excption.

### ISSUE THREAD

**Issue by pkingwsd** [SciSharp/Numpy.NET#1]
var a = np.array(new float[110_000,1024]);
            var b = np.array(new float[1024]);
            int times = 10;

            var nums = System.Linq.Enumerable.Range(0, times).Select
              (
              i =>  np.matmul(a, b)
              ); // ok

            var tasks = System.Linq.Enumerable.Range(0, times).Select
                (
                i => Task.Run(() => np.matmul(a, b))
                );
            Task.WaitAll(tasks.ToArray()); //exction

**Comment by Oceania2018** [comment]
With python gil's own limitations, I don't think it's necessary to call the same numpy object with multiple threads from outside.

https://wiki.python.org/moin/GlobalInterpreterLock

**Comment by henon** [comment]
@pkingwsd: right now, the GIL locking has not been put inside of each call to np. As stated in pythonnet you should do all calls to Python inside of the lock like this:

```csharp
Task.Run(() => {
using (Py.GIL())
{
    np.matmul(a, b);
}
});
```

Do you think it would be better to have this locking automatically in every API call or should the user put all his processing inside of a lock?  I am undecided.

**Comment by pkingwsd** [comment]
@henon : pls try it.np.matmul(a, b);// no response.
     
       var a = np.arange(1000);
            var b = np.arange(1000);
                Task.Run(() => {

                    using (Py.GIL())
                    {
                       np.matmul(a, b);// no response
                       Console.WriteLine("work");

                    }
                });

**Comment by henon** [comment]
Before using background threads you need to call `PythonEngine.BeginAllowThreads();`
Check out this issue on pythonnet that explains it: https://github.com/pythonnet/pythonnet/issues/109

```csharp
Console.WriteLine("Efficient matrix multiplication with NumPy:");
// before starting the measurement, let us call numpy once to get the setup checks done. 
var stopwatch = Stopwatch.StartNew();
np.arange(1);

var a1 = np.arange(60000).reshape(300, 200);
var a2 = np.arange(80000).reshape(200, 400);

var result = np.matmul(a1, a2);
stopwatch.Stop();

Console.WriteLine($"execution time with NumPy: {stopwatch.Elapsed.TotalMilliseconds}ms\n");
Console.WriteLine("Result:\n" + result.repr);


Console.WriteLine("executing on bg thread");

var a = np.arange(1000);
var b = np.arange(1000);

// https://github.com/pythonnet/pythonnet/issues/109
PythonEngine.BeginAllowThreads();

Task.Run(() =>
{
    using (Py.GIL())
    {
        np.matmul(a, b);
        Console.WriteLine("matmul on bg thread is done");
    }
}).Wait();
Console.WriteLine("Press key");

Console.ReadKey();
```

**Comment by pkingwsd** [comment]
awesome.
