### ISSUE TITLE
Program stuck in np.arrange

### ISSUE THREAD

**Issue by jmliu1983** [SciSharp/Numpy.NET#10]
When I try to build a NDarray using np.arrange like following:
`var a1 = np.arange(25).reshape(5, 5);`
No any exception found, but the program cannot step out from this line, it seems that it's stuck in it.
My environment:
1. VS express 2017 C#
2. .NET Framework 4.6.1
3. My application is a WinForm project.

Thanks.

**Comment by Oceania2018** [comment]
@jmliu1983 Try `x64` or upgrade .NET Framework to 4.7.

**Comment by henon** [comment]
.NET Framework 4.7 is **not** required.  Can you reproduce this with a very small example project that you can zip and attach so I can look into it? 

Sounds like a deadlock to me

**Comment by jmliu1983** [comment]
Please remove the last ext "zip", the package is about 70MB, I have to achieve into 7 parts.

[testnumpy.zip.001.zip](https://github.com/SciSharp/Numpy.NET/files/3361538/testnumpy.zip.001.zip)

**Comment by jmliu1983** [comment]
[testnumpy.zip.002.zip](https://github.com/SciSharp/Numpy.NET/files/3361544/testnumpy.zip.002.zip)

**Comment by jmliu1983** [comment]
[testnumpy.zip.003.zip](https://github.com/SciSharp/Numpy.NET/files/3361550/testnumpy.zip.003.zip)

**Comment by jmliu1983** [comment]
[testnumpy.zip.004.zip](https://github.com/SciSharp/Numpy.NET/files/3361564/testnumpy.zip.004.zip)

**Comment by jmliu1983** [comment]
[testnumpy.zip.005.zip](https://github.com/SciSharp/Numpy.NET/files/3361573/testnumpy.zip.005.zip)

**Comment by jmliu1983** [comment]
[testnumpy.zip.006.zip](https://github.com/SciSharp/Numpy.NET/files/3361577/testnumpy.zip.006.zip)

**Comment by jmliu1983** [comment]
[testnumpy.zip.007.zip](https://github.com/SciSharp/Numpy.NET/files/3361589/testnumpy.zip.007.zip)

**Comment by jmliu1983** [comment]
OK, all the codes uploaded, thanks for your checking

**Comment by henon** [comment]
I can't open it. Why are you packing the directories "packages" and "bin" and "obj" with it? Without them it should only have a few kilobytes

**Comment by henon** [comment]
also remove .vs directory and other irrelevant things

**Comment by jmliu1983** [comment]
[WindowsFormsApp1.zip](https://github.com/SciSharp/Numpy.NET/files/3362524/WindowsFormsApp1.zip)
Done, but there will be only fewo codes...

**Comment by henon** [comment]
ok, I found the problem. you need to set the compilation to x64 because numpy is 64 bit.
[WindowsFormsApp1_fixed.zip](https://github.com/SciSharp/Numpy.NET/files/3362577/WindowsFormsApp1_fixed.zip)

**Comment by jmliu1983** [comment]
Yes, It works. Thanks a lot.
Another question, it means the compiled .exe file cannot be executed in X86 operation system, correct?

**Comment by henon** [comment]
C'mon this is the 21st century 😆 . 

In earnest: Yes. If that is a problem you can always use Numpy.Bare with local Python installation or you recompile Numpy.NET with an embeeded x86 numpy wheel instead of the x64 wheel.

**Comment by jmliu1983** [comment]
u.... too complex for me as a beginner~~
Thanks a lot. I will keep use in x64, it's more easy for me~

**Comment by Oceania2018** [comment]
It's working for `Any CPU`.

![image](https://user-images.githubusercontent.com/1705364/60731593-8f5ae200-9f0d-11e9-8105-f7c5d52cdb33.png)

**Comment by henon** [comment]
It doesn't for me. If you use my upload you think it is Any CPU but it isn't because I changed it to x64 in the build settings.
