### ISSUE TITLE
Slow Conversion for 3D arrays

### ISSUE THREAD

**Issue by roushrsh** [SciSharp/Numpy.NET#106]
Hi,

np.array() a double[,,] is extremely slow. 
On an identical length 1D double[] array where it's only 2 ms (1000 items) to convert with. np.array(), for the double[,,] it's as much as 400 ms on my end.
Is there a significantly faster way of doing this?
Ex: Somehow make an empty array of 0s and fill it in?

Thanks!

**Comment by henon** [comment]
Hi @roushrsh, can you post your solution so others can us it, when they find this issue via Google?

**Comment by roushrsh** [comment]
@henon Just want to add that I have no solution yet, else I'd have added it.

If anyone has any ideas I'd love to hear them.
  
When it comes to predicting, something like Microsoft.net lets me build the model and not have to turn them into numpy, but the prediction is significantly slower on GPU compared to Keras.net. CPU is faster, but the CPU was way too slow for me to use for my application (CPU is also always occupied, so I'd rather not be using it for predictions anyways).

I'm trying to use ironpython now, but it doesn't have things like tensorflow there. 

The other 2 major ones:
tensorflow.net and scipsharp don't have dedicated model loading anyways.

Looking for any ideas to explore. Currently trying to figure out a way to write my own wrapper to have python running in the background, and just feed in C# doubles and have them assembled into my numpy dimensions inside, predicted, then output sent back.

**Comment by henon** [comment]
Ok, I got it. Numpy.NET sure is too slow for some applications such as training large neural networks because of the data conversion overhead.
