### ISSUE TITLE
np.concatenate

### ISSUE THREAD

**Issue by natank1** [SciSharp/Numpy.NET#11]
Hi   I have a data X  with the shape 700x600.

I want to have X[: 0:30,55:79].
In python we do:
y=np.arange(30)
y1 = np.arange(55,79)
X1=X[:, np.concatenate((y,y1))]

How do I do it with numyp nuget?

**Comment by natank1** [comment]
I managed to resolve it using np.hstack. However what do I do if I dont know the indices as number but as params (i.e. I Know that I need a:b not 55:79)?

**Comment by henon** [comment]
np.concatenate works, I just ported the np.concatenate test to make sure it does, and it works. Only tuples are not supported, you have to use an array.

```C#
        [TestMethod]
        public void concatenateTest()
        {
            var a = np.array(new[,] {{1, 2}, {3, 4}});
            var b = np.array(new[,] {{5, 6}});
            var given = np.concatenate(new[] {a, b}, axis: 0);
            var expected =
                "array([[1, 2],\n" +
                "       [3, 4],\n" +
                "       [5, 6]])";
            Assert.AreEqual(expected, given.repr);
            given = np.concatenate(new[]{a, b.T}, axis: 1);
            expected =
                "array([[1, 2, 5],\n" +
                "       [3, 4, 6]])";
            Assert.AreEqual(expected, given.repr);
            given = np.concatenate(new[]{a, b}, axis: null);
            expected =
                "array([1, 2, 3, 4, 5, 6])";
            Assert.AreEqual(expected, given.repr);
        }
```

Tuple of NDArrays with up to four items will be supported in the next release. Right now, use NDArray[] instead. It works.
