### ISSUE TITLE
ModuleNotFoundError : No module named 'numpy'

### ISSUE THREAD

**Issue by epignatelli** [SciSharp/Numpy.NET#12]
Hi guys,

I am currently wrapping `Numpy.NET` around a visual programming interface.
You can take a look here: https://github.com/BHoM/Numpy_Toolkit/pull/2
The code is not ready to be tested yet, but it gives you an idea of what I am doing with it.

Everything goes fine until I run into the error below:
`ModuleNotFoundError : No module named 'numpy'`

I thought `Python.Included` was taking care of setting the right environment, but it seems that it can't find the `numpy` module.

Do you have any clue why?

**Comment by henon** [comment]
wow, interesting !!

Python.Included takes care of installing the embedded Python distribution and is able to install modules into it but the modules must be provided by the caller. When you look at the source code of Numpy.NET you'll see that it ...
* embeds the win_x64 numpy wheel in its assembly
* calls Python.Included's Installer to install that wheel the first time you access np.

**Comment by epignatelli** [comment]
Thanks @henon, I have been struggling with this a little bit. 
Non-working measures I have taken:
- Add the `.whl` file as a resource the the `Numpy_Toolkit` project

Working measures:
I slightly modified the Numpy.NET, but I think that is a workaround, not a solution. Also, it is the incorrect way to solve it as I am modifying the auto-generated file. But it actually works, so I can get up and running with a prototype and fix these later. Below is the potential diff:
```c#
        private static PyObject InstallAndImport(bool force = false)
        {
            var installer = new Installer();
            installer.SetupPython(force).Wait();
            var ass = AppDomain.CurrentDomain.GetAssemblies().Where(x => x.FullName.Contains("Numpy")).FirstOrDefault();
            if (ass != null)
                installer.InstallWheel(ass, "numpy", force);
            PythonEngine.Initialize();
            var mod = Py.Import("numpy");
            return mod;
        }
```

Now, the problem is that Numpy.NET is not installing the wheel by itself. I am using the nuget package for it, and it seems like it is actually doing it at code generation time.
I had to force it install the wheel when Python is also installed.

Do you have any idea why this happens?

**Comment by henon** [comment]
Yeah, I think I know why. I recently removed the type `Numpy` which the installer was looking for. We have to use the type `np` instead now. Good catch, and sorry for the inconvenience

**Comment by henon** [comment]
You are right, the code dropped out of Numpy.NET while refactoring without me noticing, I will fix this

**Comment by henon** [comment]
@epignatelli check out np.module.get.cs, I just regenerated it with the fix. Thanks for pointing it out to me! Now I got to release a fixed Numpy.dll nuget

**Comment by epignatelli** [comment]
thanks @henon for the fix! I just updated the nuget, and all runs smoothly now - closing this as it is solved for me.

**Comment by t9mike** [comment]
Greetings. I am kicking tires and get same error with 3.7.1.9:

- Created VS.NET Windows 2019 .NET  Framework 4.6.1 console project
- Added nuget https://www.nuget.org/packages/Numpy/3.7.1.9?_src=template
- Pasted https://github.com/SciSharp/Numpy.NET/blob/master/NeuralNetworkExample/Program.cs into my Program.cs
- Run: get Python.Runtime.PythonException: 'ModuleNotFoundError : No module named 'numpy''

Is this still expected? Thank you!

**Comment by henon** [comment]
It is not expected, not any more. Can you clone the Numpy.NET repo and execute the example project? Does that fail also?

**Comment by t9mike** [comment]
Running NeuralNetworkExample from repo worked fine.

I created .NET Core 2.1 console sample from scratch and brought in the 3.7.1.9 NuGet. It ran Fine!

I retried the .NET Framework 4.6.1 project I created: it still threw the module error.

**Comment by henon** [comment]
ok, that is valuable insight. I think .NET Framework and .NET Core handle embedded resources differently. Have you also tried Numpy.Bare with a local Python installation?
