### ISSUE TITLE
Could not find platform dependent libraries <exec_prefix>

### ISSUE THREAD

**Issue by johmarjac** [SciSharp/Numpy.NET#121]
Hi,

I just created a bare minimum C# Console Application targeting .NET 6, referenced the NuGet Numpy.NET package and set my build configuration to x64

![image](https://user-images.githubusercontent.com/30114127/229482980-f8a419af-57c2-45ab-a93d-5c13d347f964.png)

![image](https://user-images.githubusercontent.com/30114127/229483018-efd955a6-6bfd-4e7c-8dbf-6fab75a314a8.png)

This code is resulting in the following output:

![image](https://user-images.githubusercontent.com/30114127/229483099-8fa6d69d-1379-4bf3-9f5d-63e94417246d.png)

Any ideas?

**Comment by johmarjac** [comment]
> 

Didnt work, I actually set it to x64 because in the README of the Repo it says I should do so. Whether I take AnyCpu or x64 doesnt change anything. I always get this message.

**Comment by henon** [comment]
OK, I can reproduce the message (don't know where it comes from) but Numpy still seems to work, so doesn't seem to be a problem on Numpy.NET's end.

![image](https://user-images.githubusercontent.com/44090/229511967-bae86bd0-bc5a-4464-b335-eab6bea28d1d.png)

**Comment by johmarjac** [comment]
![image](https://user-images.githubusercontent.com/30114127/229535043-bb272413-74e0-4be3-a13e-068dbad755fc.png)

Ah okay, first time i use numpy. Yes seems to work for me too, but just the error message was confusing me.
Thanks

**Comment by ddombrowsky** [comment]
I also get the error message, and numpy doesn't work :(

```
Syn0 = np.arange(10);
Console.WriteLine(Syn0); // hangs forever
```

This is on windows.  Too bad this is a closed ticket.

**Comment by henon** [comment]
@ddombrowsky yours is a different issue, the OP did not experience a hang. As for your problem, please read the following issues which all involve hanging: https://github.com/SciSharp/Numpy.NET/issues?q=is%3Aissue+hangs
