### ISSUE TITLE
Numpy.Bare build for Python 3.11

### ISSUE THREAD

**Issue by deepakkumar1984** [SciSharp/Numpy.NET#123]
Hi Mate, Would you be able to publish the Numpy.Bare for python 3.11 to Nuget. I see that you have done for Numpy which have the package included.

Cheers!

**Comment by henon** [comment]
Sure. Will do soon. And nice to hear from you again Deepakk! ;)

**Comment by henon** [comment]
Here you go: https://www.nuget.org/packages/Numpy.Bare/3.11.1.33
