### ISSUE TITLE
np.sum(NDArray, axis:1) not supported?

### ISSUE THREAD

**Issue by Weikang01** [SciSharp/Numpy.NET#124]
`NDArray test = np.ones(new Shape(2,2));`
`Debug.Log(np.sum(test, axis: 1));`
![image](https://github.com/SciSharp/Numpy.NET/assets/44337630/707cb380-070c-4188-892e-cba34fcde990)

Hello guys, I am running this code on Unity, but it seems unsupported. Thank you for your hard-working and it is a very helpful library!;)
![image](https://github.com/SciSharp/Numpy.NET/assets/44337630/e69a722e-14c1-47e1-b98c-39c535b08456)

**Comment by Weikang01** [comment]
By the way, I just find a temporary solution, which is using `NDArray.shape[1] * np.mean(NDArray, axis=1)` to replace the `np.sum(NDArray, axis=1)` statement.
![image](https://github.com/SciSharp/Numpy.NET/assets/44337630/77f7f084-3ffe-4631-b821-b436a76fa475)
But, since there are divisions involved, there may be some loss of accuracy for the final result, but this is the best solution I can think about right now.

**Comment by henon** [comment]
I will look into it.

**Comment by Weikang01** [comment]
Thank you, @henon ! Just to let you know, the version I'm using now is the **NumSharp.0.30.0** installed from NuGet. Thank you again for your contribution!;)

**Comment by henon** [comment]
Aha, you are not in the correct github repo, this is Numpy.NET not NumSharp. In Numpy.NET this code works without problems:

```c#
var test = np.ones(new Shape(2, 2));
Console.WriteLine(np.sum(test, axis: 1));
```
Output: `[2. 2.]`

**Comment by Weikang01** [comment]
Thank you, man! Your work is awesome! 👍
