### ISSUE TITLE
np.loadtxt

### ISSUE THREAD

**Issue by ronedmeades** [SciSharp/Numpy.NET#14]
For the method np.loadtxt there is no dtype: np.str, what are you supposed to use instead?

**Comment by henon** [comment]
I'll check it out and add what's missing.

**Comment by henon** [comment]
hmm, I don't really understand how numpy is used with strings at all, that probably is the reason why the support is not great at the moment. I ported two of the three examples from the np.loadtxt docs and they work:

```c#
        [TestMethod]
        public void loadtxtTest()
        {
            // >>> from io import StringIO   # StringIO behaves like a file object
            // >>> c = StringIO(u"0 1\n2 3")
            // >>> np.loadtxt(c)
            // array([[ 0.,  1.],
            //        [ 2.,  3.]])
            // 

            string tempFile = Path.GetTempFileName();
            File.WriteAllText(tempFile, "0 1\n2 3");
            var given=  np.loadtxt(tempFile);
            var expected=
                "array([[0., 1.],\n" +
                "       [2., 3.]])";
            Assert.AreEqual(expected, given.repr);


            // >>> c = StringIO(u"1,0,2\n3,0,4")
            // >>> x, y = np.loadtxt(c, delimiter=',', usecols=(0, 2), unpack=True)
            // >>> x
            // array([ 1.,  3.])
            // >>> y
            // array([ 2.,  4.])
            // 

            File.WriteAllText(tempFile, "1,0,2\n3,0,4");
             var a=  np.loadtxt(tempFile, delimiter:",", usecols:new []{0, 2}, unpack:true);
             given=  a[0];
             expected=
                "array([1., 3.])";
            Assert.AreEqual(expected, given.repr);
             given=  a[1];
             expected=
                "array([2., 4.])";
            Assert.AreEqual(expected, given.repr);
        }
```

Can you show me a similar simple use case for your problem? Like a few lines on the interactive Python console (similar to the ones above in the test case) so I can write a test case from it?

**Comment by henon** [comment]
by the way, there is `np.unicode_`

**Comment by ronedmeades** [comment]
I've got to sleep but one other thing (I guess I do a lot with strings) but
can we have the 'fit_on_texts' and 'texts_to_matrix' functions connected up
from keras?  They are in keras.preprocessing.text import Tokenizer.  You
create a new Tokenizer an then it exposes those methods.  Its useful when
training models to deal with things like categorizing company names.
Thanks for all the hard work, Ron

**Comment by ronedmeades** [comment]
Yes, I did see that.

**Comment by ronedmeades** [comment]
Yeah, I got it all working in the end but it was too slow re training and
so in the end I just wrote my own neural network.  But I do like the
implementation.  Thanks.
