### ISSUE TITLE
HOW to convert “Numpy.NDarray”to“OpenCvSharp.Mat

### ISSUE THREAD

**Issue by Jasonfinish** [SciSharp/Numpy.NET#15]
i want to use NDarray as Image, for showing in c#picturebox. but it dose not work!

**Comment by Jasonfinish** [comment]
anybody can help me ?

**Comment by henon** [comment]
Please post a small code example of what you are trying to do.

**Comment by simonbuehler** [comment]
hi, have the same question, how would i convert this code:
``` 
rects = detector.detectMultiScale(gray, scaleFactor=1.1,minNeighbors=5, minSize=(30, 30),flags=cv2.CASCADE_SCALE_IMAGE)
    # ensure at least one face was found before continuing
    if len(rects) > 0:
        # determine the largest face area
        rect = sorted(rects, reverse=True,key=lambda x: (x[2] - x[0]) * (x[3] - x[1]))[0]
        (fX, fY, fW, fH) = rect
        # extract the face ROI from the image, then pre-process
        # it for the network
        roi = gray[fY:fY + fH, fX:fX + fW]
        roi = cv2.resize(roi, (48, 48))
        roi = roi.astype("float") / 255.0
        roi = img_to_array(roi)
        roi = np.expand_dims(roi, axis=0)
        
        # make a prediction on the ROI, then lookup the class# label
        preds = model.predict(roi)[0]
```
so here the input is a opencv mat and keras needs the nparray of the rectangle

**Comment by henon** [comment]
Which library are you using to call openCV ?

**Comment by simonbuehler** [comment]
I'm using opencvsharp

currently i'm at this state below which looks  fishy - but loading the ` Model.LoadModel("epoch_90.hdf5");` throwing a `EEFileLoadException` keeps me from testing if it works yet 

```
Mat roi = frameMat[rects[0]];
Cv2.Resize(roi, roi, new OpenCvSharp.Size(48, 48));
float[] result;
roi.GetArray(out result);
var test = np.asfarray(result) / 255;
test = ImageUtil.ImageToArray(test);
test = np.expand_dims(test, 0);

NDarray nDarray = model.Predict(test[0]);
Console.WriteLine(nDarray.argmax());
```

**Comment by henon** [comment]
Is it possible to extract the array values from the OpenCV mat into a C# array? Then you can create an NDarray from those easily and pass it on to Keras

**Comment by Oceania2018** [comment]
@simonbuehler Take a look at [SharpCV](https://github.com/SciSharp/SharpCV). It combines the `NDArray` and `Mat`.
