### ISSUE TITLE
Numpy.NET multiple instances? 

### ISSUE THREAD

**Issue by SigmaQ** [SciSharp/Numpy.NET#16]
I'm having trouble after instantiating and computing all Numpy tasks (successfully) - to refresh or load program again within another software (c# based). If i make a change to a parameter the whole process should refresh with set new parameter - yet it crashes completely like I'm still locked in the previous process. Really difficult to have a coherent debug/output since projects are being run within another software. 
Even if I remove the project (should be clear) and re-add it - it just doesn't render anything 2nd time and onward ... like somehow memory isn't cleared - still part of the same static. Tried a simple ndarray generate.

Am I missing something? Should I start handling the python runtime? with lock and releaselock?

**Comment by henon** [comment]
Are you following [this rule](https://github.com/SciSharp/Numpy.NET#multi-threading)?

**Comment by SigmaQ** [comment]
Yes, I read probably all discussions related too, including this exception it throws.
" System.DllNotFoundException: Unable to load DLL 'python37': The specified module could not be found. (Exception from HRESULT: 0x8007007E) " 
Tried everything from manually placing the dll to referencing to changing the path. It just doesn't work.

But right now it wouldn't surprise me if I'm missing something - went trough this back and forth so many times by now. And frankly I don't understand how these events are happening in the background. Have VS 2017 with python packages pre-installed + Numpy.NET's own python addons.

**Comment by SigmaQ** [comment]
No worries, 
I tried again everything, reinstalled, updated, downgraded. Revisited some similar issues and no matter what i set or change i keep getting this output.

> System.DllNotFoundException: Unable to load DLL 'python37': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

If you have any other ideas i could try? Build is successful always but code stops(DllNotFound) anytime i call python engines and wish to manage runtime as in "the rule" mentioned or any other fixes that worked for others in previous similar issues.

Thank you for your time

**Comment by henon** [comment]
You could try setting the path to Python directly (not via env var) by 
```PythonEngine.PythonHome="...";```

I recall a similar issue in the Keras.NET repo that was resolved

**Comment by henon** [comment]
by the way, this could be why it didn't work for you: Folder Permissions

see: https://github.com/henon/Python.Included/pull/8

**Comment by SigmaQ** [comment]
So I've tried testing separately both cases of Local or Roaming as environment (with python in both of them). Still same exception thrown. 
Started a new project set up everything and this time installed Numpy.Bare and weirdly same exception was thrown. It's not that it doesn't find it - it cannot open/use it. And this happens only when I want to handle Runtime cause otherwise it works and computes ndarrays, but crashes upon multiple instances.
Project is set to have full access to any permissions so quite frankly this eludes me.

**Comment by henon** [comment]
can you narrow it down by writing a very short console program that reproduces it, then paste that Program.cs here?

**Comment by SigmaQ** [comment]
I actually expected this to work now, cause it's a simple console. 
So in this case I used initialize but anything that calls Python.Runtime will throws this exception.
Repo: [Program](https://github.com/SigmaQ/TestNumpyNET)

**Comment by henon** [comment]
OK, I executed it and could reproduce the exception. Then I unchecked Prefer 32-bit and it worked:
![image](https://user-images.githubusercontent.com/44090/66716501-a80d4a80-edce-11e9-9f10-ea4a8975cc13.png)

This is because Numpy.NET packages `numpy-1.16.3-cp37-cp37m-win_amd64.whl` which was compiled for 64bit.

**Comment by SigmaQ** [comment]
Did just that and still throws in the same exception - even with target set to x64. 
And in my initial project I have it unchecked.(tried kind of everything before) I think there's something wrong with my machine. 
I have both 2019 and 2017 VS but use the 2017 one due to compatibility issues with my projects and also PyCharm. Is there a way all these 3 could mess things up? 

I suppose you have answered my question, especially if you had a successful run on the console program. I will try everything on a different machine from scratch and probably reinstall the OS asap.

Thank you for your time!

**Comment by henon** [comment]
No problem. 
Be sure to try on another machine before you go through the hassle of setting up the OS anew.  

I also use VS2017 and PyCharem. Side note: I had to downgrade the project to .NET Framework 6.4.2 before running because I haven't installed 7.4.1 yet.
