### ISSUE TITLE
Create NDarray stuck in ASP.NET

### ISSUE THREAD

**Issue by jadvei** [SciSharp/Numpy.NET#18]
Hi, I try to use Numpy in ASP.NET app, and it's stuck on second call.
It's stuck in post method, in get method sometimes ok.

I try simple code

NDarray array = np.array(new float[,] { { 0 }, { 1 } });

[Test.zip](https://github.com/SciSharp/Numpy.NET/files/3689465/Test.zip)

**Comment by henon** [comment]
If you use Numpy.NET on different threads you need to follow some rules explained here: https://github.com/SciSharp/Numpy.NET#multi-threading

Basically call this at startup:
```csharp
PythonEngine.BeginAllowThreads();
```
and wrap all calls to numpy in a GIL locking block.

If that resolves your issue please close it.

**Comment by jadvei** [comment]
If I write in startup just
PythonEngine.BeginAllowThreads();
it fails with 
PyEval_SaveThread: NULL tstate
I write before it 
np.arange(1);
And now it works, but it's not beautiful, what the right way to use it?

**Comment by jadvei** [comment]
I found it, 
`PythonEngine.Initialize();`
