### ISSUE TITLE
Dispose all Pythonnet objects if numpy.net objects go out of scope

### ISSUE THREAD

**Issue by henon** [SciSharp/Numpy.NET#19]
reported here: https://github.com/SciSharp/Keras.NET/issues/40

**Comment by ZivKidd** [comment]
i meet the problem
i used several large ndarray in my code
and the variables are not disposed

**Comment by ZivKidd** [comment]
can i dispose it by myself?
do you have any idea?
thank you so much

**Comment by ZivKidd** [comment]
`        private static void test()
        {
            NDarray a = np.random.randn(5000, 5000);
        }
        private static void Main(string[] args)
        {
            for (int i = 0; i < 40000; i++)
            {
                test();
            }
        }`

**Comment by ZivKidd** [comment]
`        private static void test()
        {
            NDarray a = np.random.randn(5000, 5000);
        }
        private static void Main(string[] args)
        {
            for (int i = 0; i < 40000; i++)
            {
                test();
            }

> }`

**Comment by henon** [comment]
I guess a finalizer needs to be implemented for NDarray and other objects, i.e. in the superclass PythonObject. Can you clone the source code, implement it and find a way to test that it is working?

**Comment by ZivKidd** [comment]
thanks for your replying, I used the ((IDisposable)a).Dispose() to dispose it myself, it looks works for me
`        private static void test()
        {
            var a = np.random.randn(5000, 5000);
            var b = a["1:,1:"];
            // Mat b = new Mat(5000,5000, MatType.CV_8UC1);
            ((IDisposable)a).Dispose();
            ((IDisposable)b).Dispose();
            // GC.Collect();
            // GC.WaitForPendingFinalizers();
        }
        private static void Main(string[] args)
        {
            for (int i = 0; i < 40000; i++)
            {
                Console.WriteLine(i);
                test();
            }
}`

**Comment by ZivKidd** [comment]
```
        private static void test()
        {
            var a = np.random.randn(5000, 5000);
            var b = a["1:,1:"];
            // Mat b = new Mat(5000,5000, MatType.CV_8UC1);
            ((IDisposable)a).Dispose();
            ((IDisposable)b).Dispose();
            // GC.Collect();
            // GC.WaitForPendingFinalizers();
        }
        private static void Main(string[] args)
        {
            for (int i = 0; i < 40000; i++)
            {
                Console.WriteLine(i);
                test();
            }
}
```

**Comment by henon** [comment]
ok, so maybe we should call the Dispose automatically in the finalizer then, right?

**Comment by ZivKidd** [comment]
yes, thanks for your job

**Comment by ZivKidd** [comment]
```C#
        private static void test()
        {
            NDarray a = np.random.randn(5000, 5000);
            NDarray b = np.mean(a, axis: 1, keepdims: true);

            ((IDisposable)a).Dispose();
            ((IDisposable)b).Dispose();

        }

        private static void Main(string[] args)
        {
            for (int i = 0; i < 40000; i++)
            {
                Console.WriteLine(i);
                test();
            }
        }
```

**Comment by ZivKidd** [comment]
ops, when i used np.mean, it does not work any more

**Comment by henon** [comment]
even with GC.Collect(); and GC.WaitForPendingFinalizers(); ?

**Comment by ZivKidd** [comment]
![image](https://user-images.githubusercontent.com/31679051/105028290-cfe86500-5a8b-11eb-8f09-a8aad9338d1c.png)
with GC.Collect(); and GC.WaitForPendingFinalizers(), it works a little, the memory used is like this, it looks like will dispose them after call the func every 8 times

**Comment by ZivKidd** [comment]
I am working on the PythonObject.cs, try to find a better solution, lol

**Comment by ampangboy** [comment]
Hi, pardon my intrusion. Has there been resolution to this issue?

**Comment by henon** [comment]
I looked at the disposal routines, they seem to be fine. And from the memory screenshot above you can see that memory is clearly reclaimed, so I see no bug here.
