### ISSUE TITLE
Nightly builds?

### ISSUE THREAD

**Issue by hutchk** [SciSharp/Numpy.NET#22]
Hello, I'm getting an an issue with the latest version of Numpy.NET we downloaded from NuGet and think that it might be solved in master.

Is there any way to get a debug build and verify if the issue is resolved? 

Currently the latest release is 3.7.1.9 which is 3 months old.

**Comment by henon** [comment]
That doesn't make sense, I recently released fixes to Numpy.NET. I'll check my release script

**Comment by henon** [comment]
OK, I found and fixed the problem. The recent release is https://www.nuget.org/packages/Numpy/3.7.1.10

**Comment by hutchk** [comment]
Thank you!
