### ISSUE TITLE
is there any way to convert NumSharp.NDArray to Numpy.NDarray?

### ISSUE THREAD

**Issue by lelelemonade** [SciSharp/Numpy.NET#25]

**Comment by henon** [comment]
Todo: incorporate this solution in Numpy.NET

https://github.com/SciSharp/NumSharp/issues/383#issuecomment-571107211

**Comment by henon** [comment]
By the way, it is possible now to pass a pointer to an unmanaged memory block into Numpy.NET. Check out NDarray's constructors
