### ISSUE TITLE
NDarray error initialization inside RestApi method (C#/WebApi project)

### ISSUE THREAD

**Issue by berlicon** [SciSharp/Numpy.NET#26]
Hi!
If I work with NDarray in console app there is no problem. I can initialize array and use it for prediction. But inside REST API method it works only one time. After second invokation the app freezes at line: 
var array = new float[1, 2];
var ndArray = new NDarray(array);	//freezes at this line AFTER SECOND INVOCATION
result = ndArray.ToString();

In debug session in Visual Studio (2017/2019) it produces **sometimes** error: "AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt". **Sometimes** it just hangs on the line where array was created.

See my code: 
1) Back (C#): https://github.com/berlicon/MoscowTravelHackTestApp/tree/master/back/HackApi2
2) Front (Angular.io): https://github.com/berlicon/MoscowTravelHackTestApp/tree/master/front/hack-app

Files with problems:
1) WebApi controller: https://github.com/berlicon/MoscowTravelHackTestApp/blob/master/back/HackApi2/Controllers/MainController.cs
2) Util class with model: https://github.com/berlicon/MoscowTravelHackTestApp/blob/master/back/HackApi2/Utils/ModelUtil.cs

Error in ModelUtil.TestNDarray() which invoked from WebApi method MainController.TestNDarray() with params [0, 0]

I have read the paragraph: https://github.com/SciSharp/Numpy.NET#multi-threading
And have already tried:
1) PythonEngine.BeginAllowThreads(); //app crashed at this line and exit, so I commented this line
2) Task.Run(()=> {		//no effect
  using (Py.GIL())		//no effect with or without Task.Run around
  {
	var array = new float[1, 2];
	var ndArray = new NDarray(array);	//freezes at this line AFTER SECOND INVOCATION
	result = ndArray.ToString();
  }
}).Wait();
3) ndArray.Dispose();	//Suprisingly it helps and I could invoke method without errors 5 times. But after some time it also has no effect
4) GC.KeepAlive(ndArray);  //no effect
5) using (Py.GIL()) in web api method MainController.TestNDarray()	//no effect

I tried this code at home (notebook Win10, Visual Studio 2019 community, python installed) and at work (desktop, Win10, Visual Studio 2017 Professional, Python installed) with equal results.

If I initialize NDarray from C# arrays incorrectly what is the correct way?

**Comment by henon** [comment]
One thing is for sure, when you get a AccessViolationException it is because of memory corruption. I lack the time to read your source code but you can check the Numpy.NET test suite to see what ways of creating arrays were tested and if those tests also work in your environment. 

https://github.com/SciSharp/Numpy.NET/blob/master/test/Numpy.UnitTest/NumpyTest.cs

by the way, there is one test which is not working, so be sure not do do it this way:  https://github.com/SciSharp/Numpy.NET/blob/master/test/Numpy.UnitTest/NumpyTest.cs#L27

**Comment by berlicon** [comment]
> what ways of creating arrays
I tries this way ([TestMethod] void array(), line #66):
var array = new int[] { 1, 2, 3, 4, 5, 6 };
var a = np.array(array);  //first time OK. Second time hangs out in this line
Console.WriteLine(a.repr);
![error creating ndArray inside WebApi method](https://user-images.githubusercontent.com/18382276/74237953-bb311800-4ce5-11ea-9ec3-3573fce0e496.png)

**Comment by henon** [comment]
Here it only hangs? Or do you get the corrupted memory?

**Comment by berlicon** [comment]
It only hangs now. But I checked it just for several times. I think if I will try more I will get the exception as earlier.
On screeen:
1) on first run all is OK - see Output window. It prints "array([1,2,3,4,5,6])"
2) when I invoke method second time the app has gone to the line #277 and hangs.

**Comment by berlicon** [comment]
Can you reproduce the error? In order to reproduce the bug you should just paste code to any GET/POST method of WebApi project and invoke method by URL in browser or POSTMAN etc. Also you should attach Numpy.net package to the project (add nuget package of Numpy.net last ver #3.7.1.10).
Code to paste:
var array = new int[] { 1, 2, 3, 4, 5, 6 };
var a = np.array(array);
Console.WriteLine(a.repr);
![Numpy](https://user-images.githubusercontent.com/18382276/74245213-b4a99d00-4cf3-11ea-8554-b59ad79964de.png)

**Comment by Oceania2018** [comment]
@berlicon In your `Program.cs`:
```csharp
        public static void Main(string[] args)
        {
            PythonEngine.Initialize();
            PythonEngine.BeginAllowThreads();

            CreateWebHostBuilder(args).Build().Run();
        }
```

**Comment by berlicon** [comment]
OK. I pasted code:
PythonEngine.Initialize();
PythonEngine.BeginAllowThreads();
... to the Program.cs / Main()

Now error appears at line PythonEngine.Initialize();:
Exception thrown: 'System.BadImageFormatException' in Python.Runtime.NETStandard.dll
An unhandled exception of type 'System.BadImageFormatException' occurred in Python.Runtime.NETStandard.dll An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

See my build options on screens.

![BadImage error](https://user-images.githubusercontent.com/18382276/74253294-f2acbe00-4cff-11ea-97b3-b59a1b5996ab.png)
![Build options](https://user-images.githubusercontent.com/18382276/74253300-f5a7ae80-4cff-11ea-996e-745056de7e9c.png)

**Comment by berlicon** [comment]
It seems error is because IIS Exoress runs in 64 bit mode but Python (included into Numpy.net) in 32 bit.
Is it possible to include 64 bit Python?
https://stackoverflow.com/questions/16226582/how-can-i-force-iis-express-to-run-in-32-bit-mode

**Comment by henon** [comment]
Numpy.Net is actually compiled Any CPU, but the python wheel it embeds is clearly 64bit: `numpy-1.16.3-cp37-cp37m-win_amd64.whl`. 
I think you should just try to compile Numpy.NET with Platform target "x64" to see if that solves your problem.

**Comment by QadiymStewart** [comment]
Gettin same Error Exception thrown at 0x00007FF8DDC1E4CB (python37.dll) in BlazorCPPN.exe: 0xC0000005: Access violation writing location 0x0000000000000020.

First time everything runs perfect second time throws error.

**Comment by henon** [comment]
Please try by elimination if this problem specific to numpy.net or if it happens with any calls to python functions via pythonnet. Also, try Numpy.Bare which uses the numpy wheel from the local python installation.

**Comment by berlicon** [comment]
I downloaded Numpy.net, compiled it as nuget and included into my project. Here are results:
1) ANY CPU - **in debug mode 10+ times works OK** / in runtime works 1st time only, 2+ time hangs
2) x64 CPU - in debug / in runtime modes works 1st time only, 2+ time app hangs

In both cases I used code:
var array = new float[1, 2];
var ndArray = new NDarray(array);
result = ndArray.ToString();
				
... without Py.GIL(), Task.Run and PythonEngine.Initialize(); PythonEngine.BeginAllowThreads();				
because error appears: DllNotFoundException: Unable to load DLL 'python37' or one of its dependencies

I don't understand why is the problem with local python as far as Numpy.net uses included python.

Anyway I want to use Keras.net (not Numpy.net only). I have problem with NDarray (which part of Numpy.net as I understand). But I can not setup both libs in one project:
Error	CS0433	The type 'NDarray' exists in both 'Numpy.Bare, Version=3.7.1.4, Culture=neutral, PublicKeyToken=null' and 'Numpy, Version=3.7.1.10, Culture=neutral, PublicKeyToken=null'

Could you please create WebApi project and GET-method whith NDarray creation and publish it?
In order to:
1) check that method works on your side 2+ times 
2) I could be able to check it on my side

PS: WebApi project better to create in Visual Studio (I use VS Community 2019):
File/New/Project/ASP.NET Core Web Application / .NET Core / ASP.NET Core 3.1 / API
... and paste code for creation NDarray here:
WeatherForecastController.cs / Get()

**Comment by henon** [comment]
> Anyway I want to use Keras.net (not Numpy.net only). I have problem with NDarray (which part of Numpy.net as I understand). But I can not setup both libs in one project:
> Error CS0433 The type 'NDarray' exists in both 'Numpy.Bare, Version=3.7.1.4, Culture=neutral, PublicKeyToken=null' and 'Numpy, Version=3.7.1.10, Culture=neutral, PublicKeyToken=null'
> 
If you want to use Keras.Net anyway, you should use Numpy.Bare (and not Numpy.NET). That way, you don't have that conflict.

**Comment by berlicon** [comment]
Yes, in my real project I linked Keras.net only (which included Nympy.net). But I have problem with repetable creation of NDarrays :(

Are Keras.net and Nympy.net suitable confident stack for using neural nets in real-life applications?

**Comment by henon** [comment]
Yes they are. 

Keras should use Numpy.Bare. If not, think this is an error on their side, unless they have added an installation routine to install the Keras wheel + dependencies into the embedded Python folder of Python.Included which Numpy.NET depends upon.

**Comment by henon** [comment]
I will add a WebAPI controller project to the Numpy.NET test suite so we can work together on that use case scenario.

**Comment by henon** [comment]
Check it out, it works ;)

**Comment by berlicon** [comment]
Fantastic! It works! I checked in runtime/debug modes and with Keras.net or Numpy.net installed.
The undocumented BUT CRUCIAL PART OF SOLUTION is the line in Program.cs:
 // this call initializes numpy. it is necessary to do that before PythonEngine.BeginAllowThreads()
np.arange(1);

It has to be written in spec! Why all these billion of people who use Keras.net/Numpy.net don't talk about it before? It is a mandatory part of using lib and first step, basically...

Bug could be closed. Thank you!

**Comment by henon** [comment]
ok, good idea. I updated the Multi-Threading section with this info: https://github.com/SciSharp/Numpy.NET/blob/master/README.md#multi-threading-must-read

**Comment by spshenzhou** [comment]
I have installed Keras.NET3.7.4.2 and Numpy.Bare 3.7.1.11 
but there is an error: Error CS0433 The type 'NDarray' exists in both 'Numpy.Bare, Version=3.7.1.4, Culture=neutral, PublicKeyToken=null' and 'Numpy, Version=3.7.1.10, Culture=neutral, PublicKeyToken=null'

How and Why can it happen???
@henon

**Comment by henon** [comment]
Keras is already referencing an older version of Numpy.NET.
