### ISSUE TITLE
Missing operator operator / (ValueType obj, NDarray a)

### ISSUE THREAD

**Issue by BenKalegin** [SciSharp/Numpy.NET#29]
Numpy.NET has operator 
public static NDarray operator /(NDarray a, ValueType obj)
but does not have 
public static NDarray operator /(ValueType obj, NDarray a)

**Comment by henon** [comment]
I didn't know that was possible at all

**Comment by BenKalegin** [comment]
What problems can you see? 

Python  allows to write code like `print(1 / np.arange(100, dtype="float32"))`

C# supports operator as well
`    public class Test
    {
        public static Test operator /(Test a, float f)
        {
            return new Test();
        }
        public static Test operator /(float f, Test a)
        {
            return new Test();
        }
    }
`

**Comment by BenKalegin** [comment]
@henon I would appreciate any update on this

**Comment by henon** [comment]
it is very easy to implement. I just forgot. Let me take a look real quick ...

**Comment by henon** [comment]
ok, this test passes now:

```c#

        [TestMethod]
        public void ndarray_value_div_ndarray()
        {
            // division operator
            var a = np.array(1.0, 2.0, 3.0);
            Assert.AreEqual(new[] { 0.5, 1.0, 1.5 }, (a / 2.0).GetData<double>());
            Assert.AreEqual(new[] { 6.0, 3.0, 2.0 }, (6.0 / a).GetData<double>());
        }
```
