### ISSUE TITLE
Support of C# Range operator in indexes

### ISSUE THREAD

**Issue by BenKalegin** [SciSharp/Numpy.NET#30]
when I convert python code 
```
time_train = time[:split_time]
time_valid = time[split_time:]
```

to Numpy.Net, the only way I found was to use formatted strings:
```
var time_train = time[$":{split_time}"];
var time_valid = time[$"{split_time}:"];
``` 

C# language recently introduced Range, I think it would be nice to support it for readability (currently it raises exception):
```
var time_train = time[..split_time];
var time_valid = time[split_time..];
```

**Comment by henon** [comment]
First of all, it is not true, that you can only use strings. You can also use `time[new Sice(start:null, stop:split_time)]` to get the same as Python: `time[:split_time]`

But of course implementing the new range operators is a fine idea. Would you care to PR?

**Comment by BenKalegin** [comment]
@henon I have a branch implementing this.  Target framework in libraries will be updated  netstandard2.0 -> netstandard2.1 and netcoreapp2.1 -> netcoreapp3.0. 
Do you think it will be ok to merge?

**Comment by henon** [comment]
It is worth a try, please PR

**Comment by YounGCoder09** [comment]
time[new Sice(start:null, stop:split_time)] -> this operation is too slower , c# waits for a long time if i have to slice repeatedly , any other way to index

**Comment by henon** [comment]
> time[new Sice(start:null, stop:split_time)] -> this operation is too slower , c# waits for a long time if i have to slice repeatedly , any other way to index , for the same operations python completes in few seconds , c# takes 5-6 mins

please don't hijack other's issues. this should be opened as separate issue. also, please add code in both C# and Python so I can reproduce the performance difference you are experiencing.

**Comment by YounGCoder09** [comment]
True I opened a separate issue already
