### ISSUE TITLE
Getting an NDarray from a Bitmap

### ISSUE THREAD

**Issue by jayouimet** [SciSharp/Numpy.NET#34]
Hello,
 
I am trying to get an NDarray from a Bitmap object, so first I tried to save it as a jpg and using ```Keras.NET's ImageUtil.LoadImg()``` then ```ImageUtil.ImageToArray()``` to get a NDarray, it works, but sometimes, the first function seemed to crash and the error stays into the Python.Runtime, so I am trying to stay away from that.

I noticed I could maybe construct an NDarray through that constructor :
```NDarray(IntPtr dataPtr, long dataLength, Dtype dtype)```

Does it mean I would be able to transform the Bitmap object into a byte array and construct it with it?

**Comment by henon** [comment]
if you can extract a byte[] from the image then you can easily create an NDarray from it using the approbriate constructor (i.e. nd.array( )). 

As for creating an NDarray from a pointer to unmanaged memory, it doesn't work currently. The thing is, we know that it can be done by executing a python script and there are instructions at https://pastebin.com/4hANmBNy how to do it. 

I tried to port what the script does to C# but it didn't work, check out the code:

```C#
        /// <summary>
        /// Creates an array from an unmanaged (or fixed) memory pointer without copying.
        /// </summary>
        /// <param name="dataPtr">Pointer to a block of unmanaged memory or to a block of pinned managed memory</param>
        /// <param name="dataLength">The length of the block of memory in bytes</param>
        /// <param name="dtype">The data type of the resulting NDarray</param>
        public NDarray(IntPtr dataPtr, long dataLength, Dtype dtype) : base()
        {
            // adapted from https://pastebin.com/4hANmBNy
            // thanks to Eli Belash
            //var g = (Numpy.ctypes.dynamic_self.c_uint8 * dataLength).from_address(dataPtr.ToInt64());
            //self = np.dynamic_self.frombuffer(g, dtype.PyObject);

            // the above does not work :( so we'll try to execute the python script (https://pastebin.com/4hANmBNy) which should work 100% according to Eli
        }
```

I created this test for the above constructor and it just kept getting memory corruptions:

```C#
        [Ignore("This does not work :(")]
        [TestMethod]
        public unsafe void create_from_pointer_without_copying()
        {
            IntPtr pointer=IntPtr.Zero;
            try
            {
                var dtype = np.int32;
                const int length = 1024;
                pointer = Marshal.AllocHGlobal(length);
                var ptr = (int*)pointer;
                // fill the buffer with index numbers
                for (int i = 0; i < length/sizeof(int); i++)
                    ptr[i] = i;
                var a = new NDarray(pointer, length, dtype);
                Console.WriteLine(a.ToString());
                Assert.AreEqual(np.arange(length), a);
            }
            finally
            {
                if (pointer!=IntPtr.Zero)
                    Marshal.FreeHGlobal(pointer);
            }
        }
```

The test should be ok, must be the implementation in the constructor that is wrong. 

The second route to get it to work is just following Eli's example on pastebin. It seems to work for Eli. It is probably quite easy to implement, just nobody found the time to do it.

**Comment by henon** [comment]
I tried again and got it to work. Haven't seen any memory corruptions, yet. Can you test?

**Comment by jayouimet** [comment]
I had actually never noticed the np.array method, it worked perfectly using it, thanks!
I will dig into Eli's way of doing it but I am not sure if I will be able to implement it as I am still unexperimented with python, I will update if I am able to get a positive results with it, thanks again!

**Comment by henon** [comment]
> I had actually never noticed the np.array method, it worked perfectly using it, thanks!
Great. Just know, this will copy the whole array. 

> I will dig into Eli's way of doing it but I am not sure if I will be able to implement it as I am still unexperimented with python, 

Not necessary for you to implement it, seems that I solved it today. Just keep it in mind, it allows to pass a pointer to a block of unmanaged memory to Python without copying it.

> I will update if I am able to get a positive results with it, thanks again!
You're welcome!

**Comment by FatemehEsfahani** [comment]
Base on the above discussion, I did not fully understand if still there is a bug in ImageUtil.LoadImg() or ImageUtil.ImageToArray for loading images or not?
Thank you for your help.

**Comment by henon** [comment]
ImageUtil has nothing to do with Numpy.NET. This discussion is about accessing the raw data of an NDarray in order to use it in another library.

**Comment by FatemehEsfahani** [comment]
@henon Thank you for your reply.
