### ISSUE TITLE
How can I translate it to C# ?

### ISSUE THREAD

**Issue by Wuhaotiandl** [SciSharp/Numpy.NET#36]
```
>>> import numpy as np
>>> a = [1,2,3,4,0,0,1,2]
>>> a = np.array(a)
>>> b = np.where(a == 0)
>>> b
```
b = np.where(a == 0)

**Comment by henon** [comment]
First thing you need to understand here is that whenever a python function clashes with a C# keyword I used the @ prefix instead. so `np.where` in python becomes `np.@where` in Numpy.NET

**Comment by henon** [comment]
the operator == between array and scalar is missing, I am adding it

**Comment by henon** [comment]
Forget about the @ it is optional. Just a precaution by the code generator. An overload for np.where was missing that took only the condition array. I added that. Now your test case is working:

```c#
        [TestMethod]
        public void np_where()
        {
            //>>> import numpy as np
            //>>> a = [1, 2, 3, 4, 0, 0, 1, 2]
            //>>> a = np.array(a)
            //>>> b = np.where(a == 0)
            //>>> b
            //(array([4, 5], dtype = int64),)
            var a = np.array(new[] { 1, 2, 3, 4, 0, 0, 1, 2 });
            var b = np.@where(a.equals(0));
            Assert.AreEqual("(array([4, 5], dtype=int64),)", b.repr);
        }
```

I am releasing the changes on nuget today.

**Comment by Wuhaotiandl** [comment]
I appreciate your work. Actually, I realize it by exist way:
`
  public static NDarray Where(NDarray target, int compare)
        {
            NDarray _targe = target.copy();
            _targe = _targe.reshape(-1);
            _targe = np.equal(_targe, (NDarray)compare);
            var itt = np.nonzero(_targe);
            return TransNdarryToNdarry(itt);
        }

        private static NDarray TransNdarryToNdarry(NDarray[] array)
        {
            NDarray sample = np.ones(array[0].len);
            for (int i = 0; i < array[0].len; i++)
            {
                sample[i] = array[0][i];
            }
            return sample.astype(np.int32);
        }
`
I will read your source code and change my code

**Comment by Wuhaotiandl** [comment]
I appreciate your work. Actually, I realize it by exist way:
`        public static NDarray Where(NDarray target, int compare)
        {
            NDarray _targe = target.copy();
            _targe = _targe.reshape(-1);
            _targe = np.equal(_targe, (NDarray)compare);
            var itt = np.nonzero(_targe);
            return TransNdarryToNdarry(itt);
        }`
I will read your source code and change mine
