### ISSUE TITLE
GetData does not match the values in the numpy array

### ISSUE THREAD

**Issue by gitpiped** [SciSharp/Numpy.NET#37]
Hi there, basically I have a 3x3 array of integers, which I then convert back to c# int[] array by using the instance method .GetData<int>(). 

If I use it on an array after it was subject to some transformations, namely flipping axis and sometimes transpose (via the .T property), the data obtained makes no sense. Also, doing the same operation returns different int[] array every time. Here is an example of 10x the same operation. 
The odd rows are the contents of the numpy array immediately before using GetData<int>(), while the even rows are the output of GetData<int>();

It seems to me that the GetData method could be getting its values from the wrong memory address. 
Numpy ndarray: [-1  0  0  0  0  0  0  0  0]
.GetData<int>(): -1 0 0 0 -447433968 -2147442432 7929956 6357102 6881389
Numpy ndarray: [-1  0  0  0  0  0  0  0  0]
.GetData<int>(): -1 0 0 0 -469519893 -1946141184 -1 0 0
Numpy ndarray: [-1  0  0  0  0  0  0  0  0]
.GetData<int>(): -1 0 0 0 -461065888 -1879043840 3 0 3
Numpy ndarray: [-1  0  0  0  0  0  0  0  0]
.GetData<int>(): -1 0 0 0 -463497665 -2147463936 0 0 0
Numpy ndarray: [-1  0  0  0  0  0  0  0  0]
.GetData<int>(): -1 0 0 0 -438135142 -1879020032 -1206988752 542 0
Numpy ndarray: [-1  0  0  0  0  0  0  0  0]
.GetData<int>(): -1 0 0 0 -425946756 -1946109952 0 0 0
Numpy ndarray: [-1  0  0  0  0  0  0  0  0]
.GetData<int>(): -1 0 0 0 -425619111 -1879003392 3 0 3
Numpy ndarray: [-1  0  0  0  0  0  0  0  0]
.GetData<int>(): -1 0 0 0 -419589731 -2147433728 0 0 0
Numpy ndarray: [-1  0  0  0  0  0  0  0  0]
.GetData<int>(): -1 0 0 0 -419720813 -1946107648 0 0 0
Numpy ndarray: [-1  0  0  0  0  0  0  0  0]
.GetData<int>(): -1 0 0 0 -409563018 -1878980096 3 0 1

Cordially, 

Martin

**Comment by henon** [comment]
This is very interesting. Could you give me a short piece of code which I can fashion into a unit test to reproduce and fix it?

**Comment by gitpiped** [comment]
Here you go!
`
using System;
using Numpy;

namespace Test
{
    class Program
    {
        static void Main(string[] args)
        {
            NumpyGlitch();
        }

        static void NumpyGlitch()
        {

            int[,] X = new int[3, 3];
            X[0, 0] = -1;

            NDarray npX = np.array(X, dtype: np.int32); // control
            NDarray npY = np.array(X, dtype: np.int32); // test

            Console.WriteLine("Control:");
            Console.WriteLine(npX);

            Console.WriteLine("Test:");
            Console.WriteLine(npY);

            // flip on the row axis
            npY = np.flip(npY, new int[] { 0 });
            Console.WriteLine("Test flipped on axis 0:");
            Console.WriteLine(npY);

            // get their data
            int[] cX = npX.GetData<int>(); 
            int[] cY = npY.GetData<int>();

            Console.WriteLine("Control extracted back to C#:");
            PrintArray(cX); // control is fine
            Console.WriteLine("Test extracted back to C#:");
            PrintArray(cY); // this one has some funny business going on!

        }

        static void PrintArray(int[] array)
        {
            for (int i = 0; i < array.Length; i++)
            {
                Console.Write("{0} ", array[i]);
            }
            Console.WriteLine();
        }
    }
}`

Thanks!

**Comment by henon** [comment]
I fixed it. Now the output looks correct:
```text
Control:
[[-1  0  0]
 [ 0  0  0]
 [ 0  0  0]]
Test:
[[-1  0  0]
 [ 0  0  0]
 [ 0  0  0]]
Test flipped on axis 0:
[[ 0  0  0]
 [ 0  0  0]
 [-1  0  0]]
Control extracted back to C#:
-1 0 0 0 0 0 0 0 0 
Test extracted back to C#:
0 0 0 0 0 0 -1 0 0 
```

It was due to the flipped array's data layout not being contiguous. In such cases GetData now calls `np.ascontiguous` internally and gives back the data of the contiguous copy.

**Comment by gitpiped** [comment]
Great, thanks!
