### ISSUE TITLE
Error while installing this Nuget Package in .net 4.5 

### ISSUE THREAD

**Issue by arn48** [SciSharp/Numpy.NET#39]
Couldn't install any version from Nuget which targets .net 4.5

**Comment by henon** [comment]
can you use .net 4.7? I think it should work.

**Comment by arn48** [comment]
no I have no choice to change the framework. This package should work at least on 4.5.

**Comment by henon** [comment]
I compiled it for .NETFramework 4.5.2, Windows and Python3.7. https://www.nuget.org/packages/Numpy.Bare.Dotnet/

I hope this works for you. Still need to figure out a way to automatically release it for all Python versions, and all platforms.
