### ISSUE TITLE
np.unique throwing null reference exception

### ISSUE THREAD

**Issue by deepakkumar1984** [SciSharp/Numpy.NET#4]
Trying to run the following code:

var hstack = np.hstack(new NDarray[] { X });
var unique = hstack.unique();

![image](https://user-images.githubusercontent.com/6328361/60076400-9c860d00-9766-11e9-9990-4d502fb42a4f.png)

I think the hstack returns a list which need to be converted. Not sure if there is any other scenario which will return PyTuple.

**Comment by henon** [comment]
I am on it

**Comment by henon** [comment]
This is a case where the return value is a tuple only if certain parameters are given. I have to split unique in multiple overloads.
