### ISSUE TITLE
Complex numbers

### ISSUE THREAD

**Issue by nlhnt** [SciSharp/Numpy.NET#41]
Hello,
I noticed there's no complex numbers support for this binding.
There's some _standard_ for those in C# [System.Numerics](https://docs.microsoft.com/pl-pl/dotnet/api/system.numerics.complex?view=netstandard-2.1).
Has this been considered?

If yea, then sorry for this spam.

**Comment by henon** [comment]
No, sorry, Complex is not yet supported.

**Comment by nlhnt** [comment]
Ok, thanks for the reply, closing the issue and sorry for the spam.

**Comment by henon** [comment]
It is not spam, since it will help others too who search the same topic. By the way, which functions that work with complex numbers would you need?

**Comment by henon** [comment]
@nlhnt complex numbers have been supportet now. see https://github.com/SciSharp/Numpy.NET/issues/51
