### ISSUE TITLE
numpy deadlock

### ISSUE THREAD

**Issue by LittleLittleCloud** [SciSharp/Numpy.NET#42]
Hey guys, how to uses numpy.net in await/async function?

the example below will cause deadlock sometimes.

```
            foreach(var i in new int[] { 1, 2, 3, 4 })
            {
                await Task.Run(() =>
                {
                    var x_train = np.arange(0, 100, 1);
                });
            }
```

**Comment by LittleLittleCloud** [comment]
OK seems that it's all clear in readme.md.... My bad

**Comment by henon** [comment]
No worries. Others will find your Issue via Google and it will be of help for them ;)
