### ISSUE TITLE
np.array issue

### ISSUE THREAD

**Issue by mfagerlund** [SciSharp/Numpy.NET#44]
H!

Maybe I'm missing something, but this works in python;
a=np.array([1,2,3])
np.array((a,a,a))
Out: 
array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

np.array([a,a,a])
Out: 
array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In Numpy.net I tested;

np.array((a, a, a)); // fails (Can not convert type of given object to dtype)
np.array(new []{a, a, a}); // fails (Can not convert type of given object to dtype)

Stack works;
 WriteLine(np.stack(new[] { a, a, a })); // works as expected
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]

np.stack((a, a, a)); // Does not compile

I solved my problem with stack, but I think np.array should work for this case?
/mattias

**Comment by henon** [comment]
yeah, numpy uses tuples a lot. the problem is that tuples are pretty useless in c# except if you know exactly what their dimensions are. But of course, using an array should work. I'll add an overload.

**Comment by mfagerlund** [comment]
Thanks  - the overloads are all manually added? No sweet automation going on?

/m

**Comment by henon** [comment]
I add manual overloads only if the API generator isn't able to produce them. actually, on closer inspection the overload already was there, it just wasn't picked by the type system. I had to add a very specific overload `np.array(NDarray<T>[] arrays)` so it would pick the correct one in this instance. 

here we go, this now works fine:

```c#
        [TestMethod]
        public void array2Test()
        {
            //>>> a=np.array([1, 2, 3])
            //>>> b=np.array([a, a, a])
            //>>> b
            //array([[1, 2, 3],
            //       [1, 2, 3],
            //       [1, 2, 3]])
            var a = np.array(new[] {1, 2, 3});
            var b = np.array(new[]{a, a, a});
            Assert.AreEqual("array([[1, 2, 3],\n       [1, 2, 3],\n       [1, 2, 3]])", b.repr);
        }
```

**Comment by henon** [comment]
released to nuget as v1.16

**Comment by mfagerlund** [comment]
Great - I was able to use Numpy.NET to translate at Gaussian Mixing Model from python to C# in a matter of hours. It would have taken forever to do without the Numpy.NET system, so big thanks! 

http://ethen8181.github.io/machine-learning/clustering/GMM/GMM.html

The only oddity I ran across was the np.array issue. 

/mattias

**Comment by henon** [comment]
Glad to hear my project is of great use! Is your project something that I can link under "Projects using Numpy.NET"?

**Comment by mfagerlund** [comment]
Not really, but the amount of code is small - if there's a place where a GMM would fit in the SciSharp infrastructure, I could upload what I have.

I've only been able to find one other public GMM implementation in c#, that either means that they're rare or that they're not that useful ;)

GMM is a clustering algorithm with soft cluster membership and it can be used as a generative model.

**Comment by mfagerlund** [comment]
Woks like a charm!
