### ISSUE TITLE
 I need the python equivalent code in c#

### ISSUE THREAD

**Issue by gurelsoycaner** [SciSharp/Numpy.NET#45]
I'm having problem convert this py code 

    ex = (P2 - P1)/(numpy.linalg.norm(P2 - P1))

and
    d = numpy.linalg.norm(P2 - P1)

and 
   ez = numpy.cross(ex,ey)

I'm using .net core 3.1 and I've installed this. <PackageReference Include="NumSharp" Version="0.20.5" />

please I need the python equivalent of the above code in c#.

thanks in advance.

Nelly

**Comment by henon** [comment]
Sure, where is your problem? This test passes fine

```c#
        [TestMethod]
        public void QuestionByGurelsoycaner()
        {
            //>>> import numpy as np
            //>>> P1 = np.array([1, 2, 3, 4])
            //>>> P2 = np.array([4, 3, 2, 1])
            //>>> ex = (P2 - P1) / (np.linalg.norm(P2 - P1))
            //>>> ex
            //array([0.67082039, 0.2236068, -0.2236068, -0.67082039])
            var P1 = np.array(new[] { 1, 2, 3, 4 });
            var P2 = np.array(new[] { 4, 3, 2, 1 });
            var ex = (P2 - P1) / (np.linalg.norm(P2 - P1));
            Assert.AreEqual("array([ 0.67082039,  0.2236068 , -0.2236068 , -0.67082039])", ex.repr);
        }
```

**Comment by gurelsoycaner** [comment]
thanks for responding this fast,
I've installed  NumSharp from nuget into my project can I cannot find "np.linalg.norm" and numpy.cross(ex,ey) method/function, infact there not intellisense as it seems omitted.

In python you can do "ex = (P2 - P1)/(numpy.linalg.norm(P2 - P1)) and ez = numpy.cross(ex,ey)" and I need to perform the same operation in my c# code.

should u try it yourself I'm sure you will see what I mean.

pls your help it needed.

**Comment by henon** [comment]
I just tried, but from the source code. which nuget package version?

**Comment by gurelsoycaner** [comment]
Install-Package NumSharp -Version 0.20.5

![image](https://user-images.githubusercontent.com/5128170/85770987-28d56200-b724-11ea-929b-4131b69a1c39.png)

**Comment by gurelsoycaner** [comment]
the same problem with np.cross

![image](https://user-images.githubusercontent.com/5128170/85771430-95e8f780-b724-11ea-94b5-ba25e0e08df7.png)

**Comment by henon** [comment]
yeah, I see, NumSharp is a different repository. This is Numpy.NET.

**Comment by gurelsoycaner** [comment]
hooo, sorry abt that,

I've just installed 

and the problem its same. method missing

  <ItemGroup>
    <PackageReference Include="NumpyDotNet" Version="0.9.42" />
  </ItemGroup>


![image](https://user-images.githubusercontent.com/5128170/85773351-69ce7600-b726-11ea-9315-917b9f57e5c4.png)

**Comment by henon** [comment]
NumpyDotNet is not right either. Install this: https://www.nuget.org/packages/Numpy/

**Comment by gurelsoycaner** [comment]
thank you very very much sir, **GOD BLESS.**
you've just save my day.
