### ISSUE TITLE
Extra dimension added when using my_ndarray[other_ndarray_with_indexes]

### ISSUE THREAD

**Issue by simonbuehler** [SciSharp/Numpy.NET#47]
hi,

i think i found an difference of how numpy and numpy.net handles this case:
`bboxes` has a shape of ( 999, 4) and `keep_idx` has a shape of e.g. ( 123 )
so in numpy `bboxes = bboxes[keep_idx]` results in a shape of (123,4) while in numpy.net i get a shape of (1,123,4)

is this my mistake or is this intentional?

**Comment by henon** [comment]
can you give me a short python console listing that shows the problem, so I can reproduce?

**Comment by simonbuehler** [comment]
like this?

```
import numpy as np
bboxes = np.empty([999,4])
keep_idx = np.array([2,6,7,8,9,13])
bboxes = bboxes[keep_idx]
>>> bboxes.shape
(6, 4)
```

**Comment by henon** [comment]
```c#
[TestMethod]
        public void QuestionBySimonBuehler()
        {
            //import numpy as np
            //bboxes = np.empty([999, 4])
            //keep_idx = np.array([2, 6, 7, 8, 9, 13])
            //bboxes = bboxes[keep_idx]
            //>>> bboxes.shape
            //(6, 4)
            var bboxes = np.empty(new Shape(999, 4));
            var keep_idx = np.array(new[] {2, 6, 7, 8, 9, 13});
            bboxes = bboxes[keep_idx];
            
            Assert.AreEqual("(6, 4)", bboxes.shape.ToString());
        }
```
that passes, I guess you haven't isolated the real problem yet

**Comment by simonbuehler** [comment]
you are right, i got caught by `keep_idx = np.where(keep_idx  > threshold)`returning a tuple and not just the array which added the dimension!

**Comment by simonbuehler** [comment]
the only problem is that  i can't use the 
    np.where(keep_idx > threshold)[0]

syntax as in numpy: Python.Runtime.PythonException: "TypeError : tuple indices must be integers or slices, not tuple"

**Comment by henon** [comment]
ok, if you want, give me a minimal c# example and I'll look into it

**Comment by henon** [comment]
hmm, why does np.where return a tuple in this case? I looked at the docs and it says it returns an array https://numpy.org/doc/stable/reference/generated/numpy.where.html

**Comment by henon** [comment]
it is explained here though https://note.nkmk.me/en/python-numpy-where/

**Comment by henon** [comment]
you found a bug here. if np.where returns a tuple I must convert that into an NDarray[]

**Comment by simonbuehler** [comment]
great you already found it too, nevertheless:

```
var threshold = 0.5f;
var boxes = np.empty(new Shape(999, 4));
var scores = np.random.rand(10);
var goodstuff= np.where(scores > threshold); // Tuple , should accept np.where(scores > threshold)[0];
boxes = boxes[goodstuff]; // extra dimension
```

**Comment by henon** [comment]
how np.where works is quite unintuitive, I would never have expected it to return 1 through 5 when called like this `np.where(keep_idx > 4)[0]` but it is the correct output.

Anyway, I fixed the return type and now your code should work. Here is the updated test case:
```c#
        [TestMethod]
        public void QuestionBySimonBuehler()
        {
            //import numpy as np
            //bboxes = np.empty([999, 4])
            //keep_idx = np.array([2, 6, 7, 8, 9, 13])
            //bboxes = bboxes[keep_idx]
            //>>> bboxes.shape
            //(6, 4)
            var bboxes = np.empty(new Shape(999, 4));
            var keep_idx = np.array(new[] {2, 6, 7, 8, 9, 13});
            bboxes = bboxes[keep_idx];
            Assert.AreEqual("(6, 4)", bboxes.shape.ToString());

            //>>> np.where(keep_idx > 4)[0]
            //array([1, 2, 3, 4, 5], dtype = int64)
            var x = np.where(keep_idx > 4)[0];
            Assert.AreEqual("array([1, 2, 3, 4, 5], dtype=int64)", x.repr);
        }
```

Released as v18 on nuget.

**Comment by simonbuehler** [comment]
awesome, works!
