### ISSUE TITLE
Ubuntu env

### ISSUE THREAD

**Issue by Oceania2018** [SciSharp/Numpy.NET#5]
Can't run in Ubuntu.

`
An unhandled exception of type 'System.DllNotFoundException' occurred in Python.Runtime.NETStandard.dll: 'Unable to load shared library 'python36' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libpython36: cannot open shared object file: No such file or directory'
`

Related issue https://github.com/SciSharp/Numpy.NET/issues/2.

**Comment by Oceania2018** [comment]
Just run it successfully. make sure the pythonnet_standard is compiled with following condition:
`pythonnet/src/runtime/Python.Runtime.csproj`
`TRACE;DEBUG;PYTHON3;PYTHON36;UCS4;MONO_LINUX;PYTHON_WITH_PYMALLOC`

**Comment by Oceania2018** [comment]
@henon Could you make a corss-platform NuGet package for pythonnet_standard ? https://docs.microsoft.com/en-us/xamarin/cross-platform/app-fundamentals/nuget-multiplatform-libraries/single-codebase

**Comment by henon** [comment]
awesome, please try the nuget once it is published: https://www.nuget.org/packages/Python.Runtime.Mono/3.6.0

**Comment by henon** [comment]
and this: https://www.nuget.org/packages/Numpy.Bare.Mono/3.6.1.4

**Comment by Oceania2018** [comment]
@henon Is it possible combine them in one package ?

**Comment by henon** [comment]
why?

**Comment by msatlihan** [comment]
I am trying to run Numpy.Net with Anaconda. I had the same issue, updated the `LD_LIBRARY_PATH` to the conda env solved this issue for me but now I am getting `undefined symbol: _PyObject_NextNotImplemented` error. Which part I am doing wrong? posted the details here https://stackoverflow.com/questions/61101282/getting-undefined-symbol-pyobject-nextnotimplemented-error-when-trying-to-ru

**Comment by henon** [comment]
I don't know. To me it looks like a problem with pythonnet

**Comment by msatlihan** [comment]
I didn't install pythonnet. I suppose I need to, right? What is the correct way of doing it via Anaconda env?

**Comment by henon** [comment]
With pythonnet I mean this (my .NET Standard version of it):
https://www.nuget.org/packages/Python.Runtime.Mono

With Anaconda you should use this:
https://www.nuget.org/packages/Numpy.Bare.Mono

But I have never had time to try Numpy.Bare with Anaconda on Linux so you'll have to do trial and error.
