### ISSUE TITLE
Performance issue while using indexing 

### ISSUE THREAD

**Issue by YounGCoder09** [SciSharp/Numpy.NET#53]
@henon  any quick pointers

```c#
for (int i = 0; i <= 2212389 ; i++)
            {
                y2[new Slice(start: 5* i, stop: 5* (i + 1))]
                   = np.dot(y1[new Slice(i, i + 2 * 4)], b);

            }
```

this takes around 1-2 mins in c# and few seconds in python , 

i removed new slice and made the array static location and it is quite reasonable in C#, any suggestion to slice the array without new slice keyword

**Comment by YounGCoder09** [comment]
update : i also used indexing using $ format and it did not improve , so i think it is a general performance issue on indexing

 y2[$"{5* i}:{5* (i + 1)}"] =
                    np.dot(y1[$"{i}: {i + 2 * 4}"], b);

**Comment by henon** [comment]
> i removed new slice and made the array static location and it is quite reasonable in C#, any suggestion to slice the array without new slice keyword

can you give a full example of the slow and the "quite reasonable" versions?

**Comment by henon** [comment]
but yeah, in general, iterating over a big array is an antipattern in Numpy.NET because of the performance overhead of pythonnet's .NET-Python interop. 

If what you do can't be done by a single numpy function that calculates everything for the complete array without iterating, then I think you should rather implement it in TensorFlow.Net using a computation graph which - once it is set up - is entirely executed in the C++ computation core at best performance.

**Comment by YounGCoder09** [comment]
Hi so what I said reasonable is without using any slice or indexing,
basically here I confirmed that np. Dot is not causing the slowness

**Comment by YounGCoder09** [comment]
Hi I went through tensorflow. Net examples but couldn't relate to this,
can you please point me to a good source?

**Comment by henon** [comment]
I would look at the official tensorflow documentation, maybe get it working
in Python first, then port over to .NET.  One thing that works great is to
just load the computation tree (which you built in Python and saved to a
file) in TensorFlow.NET and execute it. There is an example for that in
Tensorflow.NET.

I am not an expert in Tensorflow myself so I can't really give you more
details.
