### ISSUE TITLE
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Numpy.Bare Version=3.7.1.4, Culture=Neutral, PublicKeyToken=null'

### ISSUE THREAD

**Issue by spshenzhou** [SciSharp/Numpy.NET#54]
I want to use c# to do machine learning. So I installed keras.NET and some other packages through NuGet in Visual Studio 2017. Here is what I have installed.
Google.Protobuf v3.12.3
Keras.NET v3.7.4.2
Microsoft.CSharp v4.6.0
Microsoft.NETCore.Targets v3.1.0
NumSharp v0.20.5
Python.Included v3.7.3.9
Pythonnet_netstandard_py37_win v2.5.1
Tensorflow.NET v0.11.8.1
System.Threading.Tasks v4.3.0
System.Text.Encoding v4.3.0
System.Runtime.CompilerServices.Unsafe v4.7.0
System.Runtime v4.3.0
System.Reflection.Primitives v4.3.0
System.Reflection.Emit.ILGeneration v4.7.0
System.Reflection v4.3.0
System.Numerics.Vectors v4.5.0
System.Memory v4.5.3
runtime.native.System v4.3.0
System.Buffers v4.5.0
System.Globalization v4.0.11
System.IO v4.3.0

Then I want to test whether it works. So I run the code from https://github.com/SciSharp/Keras.NET/blob/master/Examples/BasicSamples/XOR.cs

The code can be compiled but there is an error saying 'coule not oad file or assembly 'Numpy.bare.Version=3.7.1.4''.  
Would someone please tell me what should I do to make it correct?

**Comment by henon** [comment]
maybe you have to reference the missing package? 

https://www.nuget.org/packages/Numpy.Bare/3.7.1.4

**Comment by spshenzhou** [comment]
> maybe you have to reference the missing package?
> 
> https://www.nuget.org/packages/Numpy.Bare/3.7.1.4

Thanks. However even after I lowered the version of Numpy.Bare to v3.7.1.4 and the version of Keras.NET to v3.6.4.2 in order to meet its requirement,  the error still occured.

![numpy_bare](https://user-images.githubusercontent.com/60549439/90491551-a5a81980-e172-11ea-8f1c-57ffdf47ff12.JPG)
![keras_net](https://user-images.githubusercontent.com/60549439/90491586-b22c7200-e172-11ea-98cd-e32065fcc85d.JPG)

**Comment by henon** [comment]
the first digits of the keras version 3.6 suggest that Python 3.6 is used, not Python 3.7 as the Numpy version suggests. So yeah, something is still off, I think. Check exactly what Numpy version the Keras package depends on

**Comment by henon** [comment]
did you solve this?
