### ISSUE TITLE
Numpy not responding and freezes the system while deploy on IIS

### ISSUE THREAD

**Issue by normarclone** [SciSharp/Numpy.NET#55]
Hello! I want to use Numpy in my **.NET (Framework) MVC project**. In local IIS Express of VS, It completely works but the trouble appears when I deploy it on Win10 **IIS**. Numpy just **freeze** my system that I **can't load** any other page or reload the page used Numpy method. 
I've tried:
  - "log" to get it error message, but It just freeze and I didn't get any message. 
  - Use some simple method like `np.array(myArr)`, It still just freeze! :( 
  - Check if IIS run in 32bit mode but I found it's already ran in 64bit mode.

Would someone please tell me what should I do to make it work?

**Comment by Esther2013** [comment]
```csharp
    public class Program
    {
        public static void Main(string[] args)
        {
            PythonEngine.Initialize();
            PythonEngine.BeginAllowThreads();

            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>();
    }
```

Add these two lines:
```csharp
            PythonEngine.Initialize();
            PythonEngine.BeginAllowThreads();
```

**Comment by normarclone** [comment]
> ```cs
>     public class Program
>     {
>         public static void Main(string[] args)
>         {
>             PythonEngine.Initialize();
>             PythonEngine.BeginAllowThreads();
> 
>             CreateWebHostBuilder(args).Build().Run();
>         }
> 
>         public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
>             WebHost.CreateDefaultBuilder(args)
>                 .UseStartup<Startup>();
>     }
> ```
> 
> Add these two lines:
> 
> ```cs
>             PythonEngine.Initialize();
>             PythonEngine.BeginAllowThreads();
> ```

I can't find Program.cs. Is there any other place where I can put it??
![image](https://user-images.githubusercontent.com/52033721/92672576-2d80de00-f343-11ea-88d9-8bc955cc00f7.png)

**Comment by henon** [comment]
When you look at the Examples folder of the Numpy.NET source, there is a WebApiExample. Can you check it out please and see if that works for you? I am pretty sure it is, like Esther Hu says, that you are missing the line `PythonEngine.BeginAllowThreads();` at some point.

**Comment by henon** [comment]
ok, @Esther2013  was almost correct but not quite. You need to do this:

```c#
            // this call initializes numpy. it is necessary to do that before PythonEngine.BeginAllowThreads()
            np.arange(1);
            PythonEngine.BeginAllowThreads(); // <--- this is very important for a web server since all requests are on different threads
```

**Comment by normarclone** [comment]
Hi @henon! After solving the Dll not found problem by using 
`Environment.SetEnvironmentVariable("PATH", @"C:\Python37\",EnvironmentVariableTarget.Process);`
 `Environment.SetEnvironmentVariable("PYTHONHOME", @"C:\Python37\", EnvironmentVariableTarget.Process);`

and also add `Numpy.np.arange(1);` `PythonEngine.BeginAllowThreads();` in Startup.cs, when ever I run to this line
 `var rs = np.linalg.norm(np.array(arr1) - np.array(arr2));` 
IIS force close without any message except `Exception thrown: 'System.AccessViolationException' in Python.Runtime.dll` in VS output window
I've tried pass `PythonEngine.BeginAllowThreads();` after and before  `var rs = np.linalg.norm(np.array(arr1) - np.array(arr2));`  It still close suddenly.

**Comment by henon** [comment]
ok, so it seems in your usecase you can't use numpy.net which automatically install python in the AppData directory per default. Can you manually install python on the machine or should it be deployed automatically? Depending on the choice there are different solutions.

if you have manually set up numpy in C:\Python37 you should reference the Numpy.Bare nuget. Which do you reference?

**Comment by normarclone** [comment]
@henon 
I've tried manually set up numpy in C:\Python37 and reference Numpy.Bare but `PythonEngine.BeginAllowThreads();` still force close IIS.

**Comment by henon** [comment]
can you create a minimal reproduction project and share it on github?

**Comment by normarclone** [comment]
@henon  https://github.com/normarclone/testNumpy/ here! This is a very minimal  project.

**Comment by henon** [comment]
I solved it. You need to wrap all code that accesses numpy in `using(Py.GIL()) { ... }` in the controller:

```c#
    public class HomeController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            //Get 2 sample arrays
            double[] Feature1 = JsonConvert.DeserializeObject<List<double>>(Features.Feature1).ToArray();
            double[] Feature2 = JsonConvert.DeserializeObject<List<double>>(Features.Feature2).ToArray();

            using (Py.GIL())
            {
                //Convert it to np.array
                NDarray arr1 = np.array(Feature1);
                NDarray arr2 = np.array(Feature2);
                //Process
                var result = np.linalg.norm(np.array(arr1 - arr2)).ToString();
                //Result : "1.4386139661537802"
                return Json(result, JsonRequestBehavior.AllowGet);
            }
        }
    }
```

**Comment by henon** [comment]
In the setup you shared on github you had used my Numpy package, which installs python and numpy in the AppData directory. So installing python in C://python37 is not necessary

**Comment by henon** [comment]
And this is of course still necessary in Global.asax.cs

```c#
            // this call initializes numpy. it is necessary to do that before PythonEngine.BeginAllowThreads()
            np.arange(1);
            PythonEngine.BeginAllowThreads(); // <--- this is very important for a web server since all requests are on different threads
```

**Comment by normarclone** [comment]
Thank you @henon! Issue close here. Thank you very much 💯
