### ISSUE TITLE
Project dependencies

### ISSUE THREAD

**Issue by sli-gpsw** [SciSharp/Numpy.NET#56]
Hi
I am using LabVIEW and not good at VS, but I also wish I can benefit from use Numpy.net. after I download this project try to compile it, I received a lot of error as attached screen shot, I believe it is due to installed wrong version or missed some  dependencies, but I don't know what is the dependencies and right version to install. could you please help me on this matter?
Thanks a lot
![Untitled](https://user-images.githubusercontent.com/18432118/93073457-8dfe7b00-f6b5-11ea-810c-d23f1aa47c11.png)

**Comment by henon** [comment]
try unloading the two WebApiExample projects

**Comment by sli-gpsw** [comment]
Thanks Henon,

After I removed the two WebApi**examples Projects, however, I still receive error as attached screen shot.
![1](https://user-images.githubusercontent.com/18432118/93324252-36444900-f848-11ea-9d76-8b801874c575.PNG)

Then I guess I need to install NETStandard.Library 2.0.0 and Python.Runtime.NETStandard 3.7.1. histories as below. 

-----------------------------------------------------------------------------------------------------------------------------------------
PM> Install-Package NETStandard.Library -Version 2.0.0
  GET https://api.nuget.org/v3/registration5-gz-semver1/netstandard.library/index.json
  OK https://api.nuget.org/v3/registration5-gz-semver1/netstandard.library/index.json 1737ms
Restoring packages for E:\Numpy.NET-master\src\Numpy\Numpy.csproj...
Installing NuGet package NETStandard.Library 2.0.0.
Committing restore...
Generating MSBuild file E:\Numpy.NET-master\src\Numpy\obj\Numpy.csproj.nuget.g.targets.
Writing lock file to disk. Path: E:\Numpy.NET-master\src\Numpy\obj\project.assets.json
Restore completed in 16.16 ms for E:\Numpy.NET-master\src\Numpy\Numpy.csproj.
Successfully uninstalled 'Microsoft.NETCore.Targets 1.1.0' from Numpy
Successfully uninstalled 'Microsoft.Win32.Primitives 4.3.0' from Numpy
Successfully uninstalled 'NETStandard.Library 1.6.1' from Numpy
Successfully uninstalled 'runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0' from Numpy
Successfully uninstalled 'runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0' from Numpy
Successfully uninstalled 'runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0' from Numpy
Successfully uninstalled 'runtime.native.System 4.3.0' from Numpy
Successfully uninstalled 'runtime.native.System.IO.Compression 4.3.0' from Numpy
Successfully uninstalled 'runtime.native.System.Net.Http 4.3.0' from Numpy
Successfully uninstalled 'runtime.native.System.Security.Cryptography.Apple 4.3.0' from Numpy
Successfully uninstalled 'runtime.native.System.Security.Cryptography.OpenSsl 4.3.0' from Numpy
Successfully uninstalled 'runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0' from Numpy
Successfully uninstalled 'runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0' from Numpy
Successfully uninstalled 'runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.Apple 4.3.0' from Numpy
Successfully uninstalled 'runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0' from Numpy
Successfully uninstalled 'runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0' from Numpy
Successfully uninstalled 'runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0' from Numpy
Successfully uninstalled 'runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0' from Numpy
Successfully uninstalled 'runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0' from Numpy
Successfully uninstalled 'System.AppContext 4.3.0' from Numpy
Successfully uninstalled 'System.Buffers 4.3.0' from Numpy
Successfully uninstalled 'System.Collections 4.3.0' from Numpy
Successfully uninstalled 'System.Collections.Concurrent 4.3.0' from Numpy
Successfully uninstalled 'System.Console 4.3.0' from Numpy
Successfully uninstalled 'System.Diagnostics.Debug 4.3.0' from Numpy
Successfully uninstalled 'System.Diagnostics.DiagnosticSource 4.3.0' from Numpy
Successfully uninstalled 'System.Diagnostics.Tools 4.3.0' from Numpy
Successfully uninstalled 'System.Diagnostics.Tracing 4.3.0' from Numpy
Successfully uninstalled 'System.Globalization 4.3.0' from Numpy
Successfully uninstalled 'System.Globalization.Calendars 4.3.0' from Numpy
Successfully uninstalled 'System.Globalization.Extensions 4.3.0' from Numpy
Successfully uninstalled 'System.IO 4.3.0' from Numpy
Successfully uninstalled 'System.IO.Compression 4.3.0' from Numpy
Successfully uninstalled 'System.IO.Compression.ZipFile 4.3.0' from Numpy
Successfully uninstalled 'System.IO.FileSystem 4.3.0' from Numpy
Successfully uninstalled 'System.IO.FileSystem.Primitives 4.3.0' from Numpy
Successfully uninstalled 'System.Linq 4.3.0' from Numpy
Successfully uninstalled 'System.Linq.Expressions 4.3.0' from Numpy
Successfully uninstalled 'System.Net.Http 4.3.0' from Numpy
Successfully uninstalled 'System.Net.Primitives 4.3.0' from Numpy
Successfully uninstalled 'System.Net.Sockets 4.3.0' from Numpy
Successfully uninstalled 'System.ObjectModel 4.3.0' from Numpy
Successfully uninstalled 'System.Reflection 4.3.0' from Numpy
Successfully uninstalled 'System.Reflection.Emit 4.3.0' from Numpy
Successfully uninstalled 'System.Reflection.Emit.ILGeneration 4.3.0' from Numpy
Successfully uninstalled 'System.Reflection.Emit.Lightweight 4.3.0' from Numpy
Successfully uninstalled 'System.Reflection.Extensions 4.3.0' from Numpy
Successfully uninstalled 'System.Reflection.Primitives 4.3.0' from Numpy
Successfully uninstalled 'System.Reflection.TypeExtensions 4.3.0' from Numpy
Successfully uninstalled 'System.Resources.ResourceManager 4.3.0' from Numpy
Successfully uninstalled 'System.Runtime 4.3.0' from Numpy
Successfully uninstalled 'System.Runtime.Extensions 4.3.0' from Numpy
Successfully uninstalled 'System.Runtime.Handles 4.3.0' from Numpy
Successfully uninstalled 'System.Runtime.InteropServices 4.3.0' from Numpy
Successfully uninstalled 'System.Runtime.InteropServices.RuntimeInformation 4.3.0' from Numpy
Successfully uninstalled 'System.Runtime.Numerics 4.3.0' from Numpy
Successfully uninstalled 'System.Security.Cryptography.Algorithms 4.3.0' from Numpy
Successfully uninstalled 'System.Security.Cryptography.Cng 4.3.0' from Numpy
Successfully uninstalled 'System.Security.Cryptography.Csp 4.3.0' from Numpy
Successfully uninstalled 'System.Security.Cryptography.Encoding 4.3.0' from Numpy
Successfully uninstalled 'System.Security.Cryptography.OpenSsl 4.3.0' from Numpy
Successfully uninstalled 'System.Security.Cryptography.Primitives 4.3.0' from Numpy
Successfully uninstalled 'System.Security.Cryptography.X509Certificates 4.3.0' from Numpy
Successfully uninstalled 'System.Text.Encoding 4.3.0' from Numpy
Successfully uninstalled 'System.Text.Encoding.Extensions 4.3.0' from Numpy
Successfully uninstalled 'System.Text.RegularExpressions 4.3.0' from Numpy
Successfully uninstalled 'System.Threading 4.3.0' from Numpy
Successfully uninstalled 'System.Threading.Tasks 4.3.0' from Numpy
Successfully uninstalled 'System.Threading.Tasks.Extensions 4.3.0' from Numpy
Successfully uninstalled 'System.Threading.Timer 4.3.0' from Numpy
Successfully uninstalled 'System.Xml.ReaderWriter 4.3.0' from Numpy
Successfully uninstalled 'System.Xml.XDocument 4.3.0' from Numpy
Successfully installed 'NETStandard.Library 2.0.0' to Numpy
Restoring packages for E:\Numpy.NET-master\src\Examples\NetCoreTest\NetCoreTest.csproj...
Restoring packages for E:\Numpy.NET-master\test\Numpy.UnitTest\Numpy.UnitTest.csproj...
Install-Package : Project Numpy is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2). Project Numpy supports: netstandard2.0 
(.NETStandard,Version=v2.0)
At line:1 char:1
+ Install-Package NETStandard.Library -Version 2.0.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : One or more projects are incompatible with .NETCoreApp,Version=v2.2.
At line:1 char:1
+ Install-Package NETStandard.Library -Version 2.0.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Committing restore...
Lock file has not changed. Skipping lock file write. Path: E:\Numpy.NET-master\src\Examples\NetCoreTest\obj\project.assets.json
Restore failed in 21.31 ms for E:\Numpy.NET-master\src\Examples\NetCoreTest\NetCoreTest.csproj.
Install-Package : Project Numpy is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Project Numpy supports: netstandard2.0 
(.NETStandard,Version=v2.0)
At line:1 char:1
+ Install-Package NETStandard.Library -Version 2.0.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : One or more projects are incompatible with .NETCoreApp,Version=v2.1.
At line:1 char:1
+ Install-Package NETStandard.Library -Version 2.0.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Committing restore...
Generating MSBuild file E:\Numpy.NET-master\test\Numpy.UnitTest\obj\Numpy.UnitTest.csproj.nuget.g.props.
Generating MSBuild file E:\Numpy.NET-master\test\Numpy.UnitTest\obj\Numpy.UnitTest.csproj.nuget.g.targets.
Writing lock file to disk. Path: E:\Numpy.NET-master\test\Numpy.UnitTest\obj\project.assets.json
Restore failed in 263.84 ms for E:\Numpy.NET-master\test\Numpy.UnitTest\Numpy.UnitTest.csproj.
Executing nuget actions took 741.05 ms
Time Elapsed: 00:00:02.7109470
PM> 

-------------------------------------------------------------------------------------------------------------------------------------------

PM> Install-Package Numpy.Bare -Version 3.7.1.4
  GET https://api.nuget.org/v3/registration5-gz-semver1/numpy.bare/index.json
  OK https://api.nuget.org/v3/registration5-gz-semver1/numpy.bare/index.json 476ms
Restoring packages for E:\Numpy.NET-master\src\Numpy\Numpy.csproj...
  GET https://api.nuget.org/v3-flatcontainer/numpy.bare/index.json
  OK https://api.nuget.org/v3-flatcontainer/numpy.bare/index.json 653ms
  GET https://api.nuget.org/v3-flatcontainer/numpy.bare/3.7.1.4/numpy.bare.3.7.1.4.nupkg
  OK https://api.nuget.org/v3-flatcontainer/numpy.bare/3.7.1.4/numpy.bare.3.7.1.4.nupkg 816ms
Installing Numpy.Bare 3.7.1.4.
Installing NuGet package Numpy.Bare 3.7.1.4.
Committing restore...
Writing lock file to disk. Path: E:\Numpy.NET-master\src\Numpy\obj\project.assets.json
Restore completed in 1.72 sec for E:\Numpy.NET-master\src\Numpy\Numpy.csproj.
Successfully installed 'Numpy.Bare 3.7.1.4' to Numpy
Restoring packages for E:\Numpy.NET-master\src\Examples\NetCoreTest\NetCoreTest.csproj...
Restoring packages for E:\Numpy.NET-master\test\Numpy.UnitTest\Numpy.UnitTest.csproj...
Install-Package : Project Numpy is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2). Project Numpy supports: netstandard2.0 
(.NETStandard,Version=v2.0)
At line:1 char:1
+ Install-Package Numpy.Bare -Version 3.7.1.4
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : One or more projects are incompatible with .NETCoreApp,Version=v2.2.
At line:1 char:1
+ Install-Package Numpy.Bare -Version 3.7.1.4
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Committing restore...
Lock file has not changed. Skipping lock file write. Path: E:\Numpy.NET-master\src\Examples\NetCoreTest\obj\project.assets.json
Restore failed in 25.15 ms for E:\Numpy.NET-master\src\Examples\NetCoreTest\NetCoreTest.csproj.
Install-Package : Project Numpy is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Project Numpy supports: netstandard2.0 
(.NETStandard,Version=v2.0)
At line:1 char:1
+ Install-Package Numpy.Bare -Version 3.7.1.4
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : One or more projects are incompatible with .NETCoreApp,Version=v2.1.
At line:1 char:1
+ Install-Package Numpy.Bare -Version 3.7.1.4
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Committing restore...
Writing lock file to disk. Path: E:\Numpy.NET-master\test\Numpy.UnitTest\obj\project.assets.json
Restore failed in 318.74 ms for E:\Numpy.NET-master\test\Numpy.UnitTest\Numpy.UnitTest.csproj.
Executing nuget actions took 486.45 ms
Time Elapsed: 00:00:02.7489090
PM> 
 
-------------------------------------------------------------------------------------------------------------------------------------------
![2](https://user-images.githubusercontent.com/18432118/93324696-d26e5000-f848-11ea-90d9-6a74183e7deb.PNG)


-------------------------------------------------------------------------------------------------------------------------------------------

I struggled on this matter several days, and installed:

1 a total new Windows 10 x64 OS
2 VS2017 x64


Could you please help me on this?

BTW, the downloaded source code, file size is different, and both version has same issue.

Thanks a million

**Comment by henon** [comment]
You don't have the required SDKs installed it seems. Please google the error messages and find out what you are missing. This is not a Numpy specific issue.

**Comment by sli-gpsw** [comment]
I uninstalled VS2017, and re-installed it, with ".net core" development options, also installed a few .NET SDK like 2.0, 2.1, 3.1. then got error message gone away. I would like suggest to uniform all .NET SDK to single one version that make things more clean.
