### ISSUE TITLE
Unable to Resolve Reference "System.Security.Permissions"

### ISSUE THREAD

**Issue by ComputerCraft32** [SciSharp/Numpy.NET#57]
I am getting an error using Numpy with Unity. I followed this guide: https://medium.com/@jonfoust/using-gcp-nuget-packages-with-unity-8dbd29c42cc4

As it says, I copied everything from packages and pasted it into plugins, and made a link.xml file with all of the items. I tried deleted the obj folder as well as the packages folder, but the error still persists. Here is an image of my link.xml file:

![image](https://user-images.githubusercontent.com/64702869/93131445-ea977100-f688-11ea-899d-874eba07d49b.png)

Thank you much in advance for your help.

**Comment by henon** [comment]
That guide doesn't say anything about Numpy at all ;). What error do you get?

**Comment by ComputerCraft32** [comment]
Ah, I thought it applied to all NuGet packages in Unity.

![image](https://user-images.githubusercontent.com/64702869/93134689-f3d70c80-f68d-11ea-8af1-cc23a25c829e.png)

Here are the errors

**Comment by ComputerCraft32** [comment]
I can't use NumSharp because I am interested in particular with the rot90 of a 3d array (NumSharpd does not have a rot90).

**Comment by ComputerCraft32** [comment]
Apologies for asking again, but do you have any idea what caused this issue? I am currently stuck until I am able to install Numpy for C#.

**Comment by henon** [comment]
The error messages you showed sadly are not helpful at all, it just says 'not loaded due to errors'. Can you try to find out what exactly are the errors that it refers to?

**Comment by ComputerCraft32** [comment]
My apologies for the late response. I will attempt a clean install of Numpy without doing what the guide suggested and then post the errors.

**Comment by ComputerCraft32** [comment]
Okay, so I did what the instructions said too: First, I installed the NuGet package by doing  Project -> ManageNugetPackages and then adding Numpy bindings for C#. I got an error after that, so I referenced the DLL in my packages folder by using the Project -> AddReference. Now I'm getting this error:

![image](https://user-images.githubusercontent.com/64702869/93546370-7a524f00-f917-11ea-8649-253ebccdae47.png)


Is it possible to install NuGet packages into Unity? Is this Numpy for C# compatible with Unity?

**Comment by ComputerCraft32** [comment]
If I do add all the packages to the plugins folder, as detailed by the article, these are the errors I get:
![image](https://user-images.githubusercontent.com/64702869/93548429-0d8d8380-f91c-11ea-92d5-3b0da146c02b.png)

So it seems Numpy isn't loaded because Python.Runtime isn't loaded, and Python.Runtime isn't loaded because System.Security.Permissions isn't working. I have no idea what System.Security.Permissions is and how to add that to fix the issue,

**Comment by henon** [comment]
I know nothing about Unity, so I am as clueless as you are. How about trying to install System.Security.Permissions, maybe there is a nuget for that?

**Comment by henon** [comment]
another suggestion. if numpy.net is problematic for Unity, maybe switch to a native c# library such as NumSharp or NumSharpLite.

**Comment by ComputerCraft32** [comment]
Unfortunately the very reason I am using this version of Numpy for C# is that it as rot90. I tried installing the nuget of System.Security.Permissions and put the DLL into the plugins folder, but it made no difference. Do you know of any other NumPy librares that might have rot90?

**Comment by ComputerCraft32** [comment]
Wow! Numpy started randomly working with no compiler errors after a Unity and computer reboot. However, now I'm not sure how to convert a NDarray back to a regular C# array. The tolist() method does not exist (I use asarray to convert the other way around.) Do you have any ideas about this? Many thanks in advance.

**Comment by henon** [comment]
Please read the documentation. It's all described on the main page here: https://github.com/SciSharp/Numpy.NET#documentation

**Comment by ComputerCraft32** [comment]
Thanks, I just looked through it, but is it possible to make GetData<>() copy into a 3d array?
` NDarray arr = np.array(voxelMap);
            arr.rot90();
            voxelMap = arr.GetData<byte>();`

But then on the line  
            `voxelMap = arr.GetData<byte>();`
I get the compile error: Cannot implicity covert type byte[] to byte[,*,*,*]

**Comment by henon** [comment]
You can use my other library to access a C# array in numpy-like fashion: https://github.com/henon/SliceAndDice

Just create a `var voxels3d=new ArraySlice<byte>(voxelMap, new Shape(x,y,z));` 

then you can access with 3d coordinates: `voxels3d[1,2,3]`

**Comment by henon** [comment]
but if you need it as a 3d array you need to copy things around, unfortunately.

**Comment by ComputerCraft32** [comment]
If it works the same as a regular C# 3d array it will work for me. 
But how does 
`var voxels3d=new ArraySlice<byte>(voxelMap, new Shape(x,y,z));`
work? Does it reshape the 1d array voxelMap into a 3d array?

**Comment by henon** [comment]
no, it keeps the array as 1d and only solves the 3d indexing for you

**Comment by ComputerCraft32** [comment]
Alright. Is this correct usage of it?
`  NDarray arr = np.array(voxelMap);
            arr.rot90();
            byte[] map = arr.GetData<byte>();
            var voxels3d = new ArraySlice<byte>(map, new Shape(16, 16, 16));`

voxelMap is my primary 3d array, which I use at the beginning. I then copy the rotated data into a 1d array, which is then "made" into a 3d array that has the same indexing as a regular C# array. I'll give this a try.

**Comment by ComputerCraft32** [comment]
It would also be great if I could copy voxels3d back into voxelMap, but if that isn't possible I think I can still move forward.

**Comment by henon** [comment]
it is possible, but you have to do the copying manually, like explained here https://stackoverflow.com/questions/28113015/c-sharp-convert-1d-array-to-2d

**Comment by ComputerCraft32** [comment]
Henon, thank you so much for all this help! The issue has now been resolved and I seem to be able to get the array to rotate (will do some research to find out how to change the "axes" parameter. Many thanks for all the quick responses and support!
