### ISSUE TITLE
Data conversion issues

### ISSUE THREAD

**Issue by dafeifei0218** [SciSharp/Numpy.NET#59]
When the type is byte [], use np.asarray Conversion error. 
System.NotImplementedException:“Type System.Byte[] not supported yet in ConvertArrayToNDarray.”

np.array Yes, but the data is wrong.

**Comment by henon** [comment]
can you give me a short code snippet that reproduces the error? for fixing it, I need to test against the result from python.

**Comment by gv-collibris** [comment]
@henon I have a similar issue:

Numpy.NET version: 3.1.7.25

sample code:
```
var array = np.random.rand(10, 10);
np.asarray(Enumerable.Range(0, 10).Select(i => user_weights[i]).ToArray());
```

Exception:
 ```System.NotImplementedException
  HResult=0x80004001
  Message=Type Numpy.NDarray[] not supported yet in ConvertArrayToNDarray.
  Source=Numpy
  StackTrace:
   at Numpy.np.ConvertArrayToNDarray(Array a)
   at Numpy.np.SharpToSharp[T](Object obj)
   at Numpy.np.asarray[T](T[] a, Dtype dtype, String order)```

**Comment by henon** [comment]
asarray does not support an array of ndarrays
