### ISSUE TITLE
GetData<>() returning wrong values from NDarray

### ISSUE THREAD

**Issue by volgaone** [SciSharp/Numpy.NET#60]
Hello,
I am facing a problem with getting the values back from an NDarray into a c# array. I can manipulate the NDarrays entirely satisfactory, but GetData<>() method returns me values as if they belonged to an original, continuous array. Let me demonstrate:

```
[Test]
        public void TestNDarray()
        {
            var n = np.array(new float[,] { { 1, 2, 3 }, { 4, 5, 6 }, { 7, 8, 9 } });
            var row0 = n[0]; //extract 1st row
            var row0Data = row0.GetData<float>(); //this is correct - {1,2,3} 
            var col1 = n[":,1"]; //extract 1st column - NDarray is [2 5 8] as expected
            var col1Data = col1.GetData();//this is wrong - {2,3,4}
        }
```
I dug a bit into the code of `public T[] GetData<T>()` and it does check whether the array is contiguous... Maybe the mistake is there? But alas, `col1` does correctly indicate that it is _not_ a contiguous array - so `GetData()` should take that into account?
![image](https://user-images.githubusercontent.com/24879388/93990595-3205b780-fd83-11ea-8188-d9947abfd369.png)

Has anyone faced a similar issue? I am really stuck at this point - I have tried everything I can think of...
Thanks
Dmitry

**Comment by henon** [comment]
I'll look into it. Thanks a lot for providing a testcase!

**Comment by henon** [comment]
You must be using an old version of Numpy.NET. I remember I fixed that some versions ago. The test passes for me

```c#

        [TestMethod]
        public void IssueByVolgaone()
        {
            var n = np.array(new float[,] { { 1, 2, 3 }, { 4, 5, 6 }, { 7, 8, 9 } });
            var row0 = n[0]; //extract 1st row
            Assert.AreEqual("array([1., 2., 3.], dtype=float32)", row0.repr);
            var row0Data = row0.GetData<float>(); //this is correct - {1,2,3} 
            Assert.AreEqual("1,2,3", string.Join(",", row0Data));
            var col1 = n[":,1"]; //extract 1st column - NDarray is [2 5 8] as expected
            Assert.AreEqual("array([2., 5., 8.], dtype=float32)", col1.repr);
            var col1Data = col1.GetData();//this is wrong - {2,3,4}
            Assert.AreEqual("2,5,8", string.Join(",", col1Data));
        }
```

**Comment by volgaone** [comment]
Thanks for your prompt reply!

Looking at my dependencies...
![image](https://user-images.githubusercontent.com/24879388/94003774-9a5c9500-fd93-11ea-9525-48ac19856d2c.png)

That does seem to be the current version.
However after I've updated my package reference via nuget to 3.7.1.22 I now get an error:
`Unable to load DLL 'python38' or one of its dependencies: The specified module could not be found. (0x8007007E)'`
So I reckon I just need to isolate the exact dependencies until I get that code to work... 
Cheers
Dmitry

**Comment by henon** [comment]
dont confuse 3.7.x.y version with 3.8.x.y, the first two digits is the python version.
