### ISSUE TITLE
'tuple' object has no attribute 'ndim' when using multiple inputs

### ISSUE THREAD

**Issue by minma2000** [SciSharp/Numpy.NET#61]
My python trained model uses 4 inputs. When I tried to call the model to predict with Keras.Net, I supply the inputs like this:  loadedModel.Predict(new List<NDarray> { x1, x2, x3, x4 }) where x1,2,3,4 have been defined as NDarray. I have verified each x has correct dimension as model expected. But when executing this line, it gives this error:

AttributeError : 'tuple' object has no attribute 'ndim'

['  File "C:\\Users\\myacct\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py", line 1441, in predict\n    x, _, _ = self._standardize_user_data(x)\n', '  File "C:\\Users\\myacct\\anaconda3\\lib\\site-packages\\keras\\engine\\training.py", line 579, in _standardize_user_data\n    exception_prefix=\'input\')\n', '  File "C:\\Users\\myacct\\anaconda3\\lib\\site-packages\\keras\\engine\\training_utils.py", line 99, in standardize_input_data\n    data = [standardize_single_array(x) for x in data]\n', '  File "C:\\Users\\myacct\\anaconda3\\lib\\site-packages\\keras\\engine\\training_utils.py", line 99, in <listcomp>\n    data = [standardize_single_array(x) for x in data]\n', '  File "C:\\Users\\myacct\\anaconda3\\lib\\site-packages\\keras\\engine\\training_utils.py", line 34, in standardize_single_array\n    elif x.ndim == 1:\n']   at Python.Runtime.PyObject.Invoke(PyTuple args, PyDict kw)
   at Python.Runtime.PyObject.InvokeMethod(String name, PyTuple args, PyDict kw)
   at Keras.Base.InvokeMethod(String method, Dictionary`2 args)
   at Keras.Models.BaseModel.Predict(List`1 x, Nullable`1 batch_size, Int32 verbose, Nullable`1 steps, Callback[] callbacks) 

Any ideas on how to fix this?
The keras.net version is 3.7.4.2 installed using nuget

**Comment by henon** [comment]
I think this issue first has to be checked by the maintainer of Keras.NET to see whether or not the error is in Keras, which I believe it is. If it really is a Numpy error I then need a code snippet that doesn't involve Keras to reproduce and fix it.

**Comment by minma2000** [comment]
I posted the same to Keras.Net as https://github.com/SciSharp/Keras.NET/issues/161 so they can investigate in parallel.
