### ISSUE TITLE
Can't cast int array of 4 dimensions to a NDarray

### ISSUE THREAD

**Issue by nbustins** [SciSharp/Numpy.NET#63]
When I try to cast a 4 dimensional integer array to a NDarray I get an error:

```
int [,,,] iarr = new int[3,25,25,3];
NDarray nd = np.array(iarr);
```
**Unhandled exception. System.InvalidOperationException: Unable to cast System.Int32[,,,] to NDarray**

This is not happening when the array is 3 dimensional.

**Comment by henon** [comment]
not a big problem. I did only prepare [], [,] and [,,] until now.

**Comment by nbustins** [comment]
I was trying to execute a CNN model trained in python, passing the batch of images I've realized of this small problem.
BTW great job with this library!

**Comment by henon** [comment]
thanks! I added support for up to six dimensions. If you need even more, you can follow my lead and expand supported dimensions however high you want. Releasing this as v23 to nuget.
