### ISSUE TITLE
Incompatible with linux-arm platform

### ISSUE THREAD

**Issue by Banyc** [SciSharp/Numpy.NET#65]
When moving a Numpy.NET project from Windows platform to Linux-arm platform and run, the error pops up:

```
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'Python.Runtime, Version=2.5.1.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'Python.Runtime, Version=2.5.1.0, Culture=neutral, PublicKeyToken=null'
```

It seems that pythonnet runtime for Linux-arm is still unavailable.

**Comment by henon** [comment]
Yes, Numpy.NET deploys python compiled for windows in its standard version. But there is also the Numpy.Bare nuget which does not deploy anything. All you need to do is install python and numpy yourself and use Numpy.Bare. If you still wish to deploy a python distribution and a numpy binary automatically with your application you can do so with my deployment toolset called Python.Deployment which is part of my [Python.Included](https://github.com/henon/Python.Included) repo. I even have a [complete example](https://github.com/SciSharp/Numpy.NET/tree/master/src/Examples/CustomInstallLocationExample) for it in this repository.

**Comment by Banyc** [comment]
I have tried to add Numpy.Bare --version 3.7.23 and remove Numpy package but it can still not be able to find the python that has already installed.

**Comment by henon** [comment]
you may have to set the path. I don't know if that also works on linux, but this is what I would do on windows to be sure the python installation is found:

```c#
Environment.SetEnvironmentVariable("PATH", @"<your path to python>/python-3.7.3", EnvironmentVariableTarget.Process);
```

if that doesn't work please google the problem that pythonnet can't find the python distribution on linux. It is not really a numpy problem.

**Comment by Banyc** [comment]
Too expansive to:

1. install something on python3
1. set config on .net project
1. change config if that project runs in a different platform, or even in other architecture

**Comment by henon** [comment]
It is what it is. The pythonnet library which numpy.net is based on has to be compiled with different flags for every python version, OS platform and .net framework. Sorry, can't change that.
