### ISSUE TITLE
np.fromfile has not been implemented

### ISSUE THREAD

**Issue by Banyc** [SciSharp/Numpy.NET#66]
The output type of `np.fromfile` is `void`, which should have been `NDarray`.

Possible relative codes are here: <https://github.com/SciSharp/Numpy.NET/blob/d7dc6c9d24c8fae89828adb9312e197218fc3e9b/src/Numpy/np.array_creation.gen.cs#L1388-L1401>

**Comment by henon** [comment]
I'll fix both your issues on the weekend.

**Comment by henon** [comment]
done. released to nuget as v1.24
