### ISSUE TITLE
np.roll - Index was outside the bounds of the array

### ISSUE THREAD

**Issue by ChengYen-Tang** [SciSharp/Numpy.NET#69]
I get the following message when using np.roll.
Index was outside the bounds of the array

```
var a = np.arange(10);
a.roll(5, 1);
Console.WriteLine(a.ToString());
```

**Comment by henon** [comment]
I'll fix over the weekend

**Comment by ChengYen-Tang** [comment]
Sorry, this should be a numSharp error.

**Comment by henon** [comment]
oh, then please report there. closing this.
