### ISSUE TITLE
concatenate(NDArray[] arrays, int axis = 0) is much more time-consumed than what is in PYTHON.

### ISSUE THREAD

**Issue by tbplayer1989** [SciSharp/Numpy.NET#71]
concatenate(NDArray[] arrays, int axis = 0)  is much more time-consumed than what is in PYTHON. When I do six NDArrays concatenate in python, it spends about 1ms in python, but about 700ms in C#. WHY?

**Comment by henon** [comment]
I guess you have to ask the pythonnet guys that ;)

**Comment by tbplayer1989** [comment]
> I guess you have to ask the pythonnet guys that ;)
 It might be a long way to use sth in C#. - -
