### ISSUE TITLE
Memory Consumed On Numpy Initialization and Unable to Free it

### ISSUE THREAD

**Issue by roopeshReddy888** [SciSharp/Numpy.NET#74]
Hi,

I am using Numpy in one of my .net framework 4.8 projects. I have noticed that whenever the first call is made to numpy API's, ~200 MB of memory is consumed by the system (as shown in the performance profiler of VS) and even if I dispose the numpy objects properly and clear memory by calling GC Explicitly, that allocated memory is not freeing up. Can you help me in finding a way with which this memory consumed on allocation could be cleared. 

The video attached demonstrates the problem in an empty sample application.

Regards,
Roopesh

https://user-images.githubusercontent.com/60866938/108498414-d52b1080-72d2-11eb-9b75-cd18200ca449.mp4

**Comment by henon** [comment]
Maybe that is what the python interpreter allocates? I honestly can't help much with that.

**Comment by roopeshReddy888** [comment]
Ok. Thanks for the response Henon. Is there any python team who can help me with this?

**Comment by henon** [comment]
try this, use only pythonnet (not numpy.net) to initialize the python engine. check memory. then import numpy and check memory again. Use something similar to this snippet taken from the pythonnet homepage

```c#
static void Main(string[] args)
{
    using (Py.GIL())
    {
        dynamic np = Py.Import("numpy");
        Console.WriteLine(np.cos(np.pi * 2));

        dynamic sin = np.sin;
        Console.WriteLine(sin(5));

        double c = np.cos(5) + sin(5);
        Console.WriteLine(c);

        dynamic a = np.array(new List<float> { 1, 2, 3 });
        Console.WriteLine(a.dtype);

        dynamic b = np.array(new List<float> { 6, 5, 4 }, dtype: np.int32);
        Console.WriteLine(b.dtype);

        Console.WriteLine(a * b);
        Console.ReadKey();
    }
}
```

Find out what exactly allocates the 200mb you want to get rid of. The pythonnet guys maybe can help you answer any questions with regard to freeing memory.
