### ISSUE TITLE
Create NDArray from IntPtr

### ISSUE THREAD

**Issue by Oceania2018** [SciSharp/Numpy.NET#8]
When I get the ndarray from python:

![image](https://user-images.githubusercontent.com/1705364/60478341-02cbcd80-9c48-11e9-892b-147ae1f52729.png)

Can I create NDArray in Numpy.NET from IntPtr ?

![image](https://user-images.githubusercontent.com/1705364/60478287-ca2bf400-9c47-11e9-9557-b46fcc069fa4.png)

**Comment by henon** [comment]
it probably is possible if we allow to pass a PyObject to np.array(...) in
Numpy.NET but you don't need to do this to access the items of the
sequence. You can directly foreach over class_predictions which gives you a
PyObject for every entry which you can convert to string by using
.As<string>() or you can directly index into class_predictions either like
this [i] or with .GetItem(i)

**Comment by henon** [comment]
oh, I realize it already is an NDarray (I thought it was a normal Python array), yes you can create an NDarray from PyObject directly like this:

```C#
var a=new NDarray(class_predictions);
var a1=new NDarray<string>(class_predictions);
```

The latter is especially useful because it automatically casts elements to string if you index into it

**Comment by Oceania2018** [comment]
@henon Works, thanks mate.
