### ISSUE TITLE
np.random.choice get stuck

### ISSUE THREAD

**Issue by eliphatfs** [SciSharp/Numpy.NET#80]
I'm using Numpy.NET to write a DLL plugin for some host applications, and when I call np.random.choice the whole thing gets stuck. By attaching VS debugger and interrupting and trying to call `np.random.choice(8)` in the immediate window, VS also gets stuck.

**Comment by Oceania2018** [comment]
Same issue as https://github.com/SciSharp/Numpy.NET/issues/26

**Comment by henon** [comment]
Deadlocks are most likely caused by not following this guide: https://github.com/SciSharp/Numpy.NET/blob/master/README.md#multi-threading-must-read

**Comment by eliphatfs** [comment]
Thank you. I thought that the problem wasn't there because many non-random calls are successful before that one. As an implementation problem, is it possible to require GIL when the ctor (assigning to member fields) is executing?
