### ISSUE TITLE
The functions of np.linalg.norm not accept List<NDarray> 

### ISSUE THREAD

**Issue by cross-hello** [SciSharp/Numpy.NET#88]
In the [document](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html), the first argument is *array-alike* type. And in **Python** it is OK for input *List* as argument in np.linalg.norm.
```Python
a=[1,2,3]
b=np.array(a)# Now b is native NDArray type
c=[]
c.append(b)
c.append(b)
c.append(b)# Now c is a List which has three NDArray element
np.linalg.norm(c)
```
![image](https://user-images.githubusercontent.com/42733664/143553560-67613b84-3099-4e20-a47c-4e5b92cc0c10.png)

Now could I do the same way in Numpy.NET? I didn't find such a protocol which accept **List\<NDarray\>** as argument in *np.linalg.norm* functions, how could I do it?

**Comment by henon** [comment]
here is an example from the tests:

```c#

        [TestMethod]
        public void QuestionByGurelsoycaner()
        {
            //>>> import numpy as np
            //>>> P1 = np.array([1, 2, 3, 4])
            //>>> P2 = np.array([4, 3, 2, 1])
            //>>> ex = (P2 - P1) / (np.linalg.norm(P2 - P1))
            //>>> ex
            //array([0.67082039, 0.2236068, -0.2236068, -0.67082039])
            var P1 = np.array(new[] { 1, 2, 3, 4 });
            var P2 = np.array(new[] { 4, 3, 2, 1 });
            var ex = (P2 - P1) / (np.linalg.norm(P2 - P1));
            Assert.AreEqual("array([ 0.67082039,  0.2236068 , -0.2236068 , -0.67082039])", ex.repr);
        }
```

Btw, you can look at the tests if you download the code.

**Comment by henon** [comment]
look at this also: https://github.com/SciSharp/Numpy.NET/issues/48
