### ISSUE TITLE
Problem calling ufunc

### ISSUE THREAD

**Issue by petterton** [SciSharp/Numpy.NET#96]
I am trying to port some existing code to Numpy.NET, but I have a problem with the following line:

`np.equal.outer(a, b)`

The error message provided is
np.equal(NDarray, NDarray, NDarray, NDarray)' is a method, which is not valid in the given context

Is this not implemented in Numpy.NET, or am I missing something?

**Comment by BalashovK** [comment]
Why don't you just call them one at a time?
NDarray c = np.outer(a, b);
NDarray d = np.equal(c, e);
I have tried it and it works just fine.

I would expect that some Python syntax sugar might not be 100% implementable in C#

**Comment by henon** [comment]
Thanks @BalashovK for answering this
