### ISSUE TITLE
gradient varags not working

### ISSUE THREAD

**Issue by longdrive01923** [SciSharp/Numpy.NET#97]
Trying to call gradient in Numpy.Net with python package python.included 3.7.3.13 and getting an exception thrown when trying to pass varargs.
Exception:  Python.Runtime.PythonException:  TypeError: varargs are not valid arguments

C# code:
NDarray args = np.array( new double[]{ dx,dy});
NDarray gradArray = np.gradient( ZValues, args );   // ZValues is a 74 by 74, ndim 2

Any help would be greatly appreciated!

Thank You!
Allen

**Comment by henon** [comment]
can you give me a python console log of the same for reference?

**Comment by longdrive01923** [comment]
Ok, so in the console window I typed the python code in;

dx and dy are a float64  value of 4.0
zX is a 2D array of float64's (74,74)
!continue

!continue

np.gradient(zX,dx,dy)
Out  [2]:
[array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]]), array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]])]

Let me know if you need more info.

Thanks Again,
Allen
________________________________

**Comment by henon** [comment]
Ok, so this is gonna be the test case:

```python
>>> import numpy as np
>>> dx=4.0
>>> zX=[[1,2,3],[4,5,6],[8,9,0]]
>>> dy=5.0
>>> np.gradient(zX, dx, dy)
[array([[ 0.75 ,  0.75 ,  0.75 ],
       [ 0.875,  0.875, -0.375],
       [ 1.   ,  1.   , -1.5  ]]), array([[ 0.2,  0.2,  0.2],
       [ 0.2,  0.2,  0.2],
       [ 0.2, -0.8, -1.8]])]
>>>
```

**Comment by longdrive01923** [comment]
Perfect - I tried this and got the same exception.   I hope it just works for you and you can show me how you packaged up the varargs.

Allen

On Apr 21, 2022, at 11:03 AM, Meinrad Recheis ***@***.***> wrote:

﻿

Ok, so this is gonna be the test case:

>>> import numpy as np
>>> dx=4.0
>>> zX=[[1,2,3],[4,5,6],[8,9,0]]
>>> dy=5.0
>>> np.gradient(zX, dx, dy)
[array([[ 0.75 ,  0.75 ,  0.75 ],
       [ 0.875,  0.875, -0.375],
       [ 1.   ,  1.   , -1.5  ]]), array([[ 0.2,  0.2,  0.2],
       [ 0.2,  0.2,  0.2],
       [ 0.2, -0.8, -1.8]])]

**Comment by henon** [comment]
This is a tricky one. The gradient function is the only one in the whole numpy I could find with a `*varargs` parameter. I tried a few tricks but didn't get it working. So I opened an issue with pythonnet here: https://github.com/pythonnet/pythonnet/issues/1771

Lets hope they can give me some insight how to call the function, then I can prepare an update.

**Comment by longdrive01923** [comment]
I naturally thought I was doing something wrong.   Thank you for looking into this.

Allen

On Apr 24, 2022, at 4:56 PM, Meinrad Recheis ***@***.***> wrote:

﻿

This is a tricky one. The gradient function is the only one in the whole numpy I could find with a *varargs parameter. I tried a few tricks but didn't get it working. So I opened an issue with pythonnet here: pythonnet/pythonnet#1771<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpythonnet%2Fpythonnet%2Fissues%2F1771&data=05%7C01%7C%7C7e1bbfa5877348123d4c08da2634e68d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637864305899936189%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Sp%2Fhwj0Y9XAPSu1%2FvGoIO1e9K1Fd2K8Z3Wvifc%2B9nH8%3D&reserved=0>

Lets hope they can give me some insight how to call the function, then I can prepare an update.

**Comment by henon** [comment]
I got some feedback from the pythonnet guys here: https://github.com/pythonnet/pythonnet/discussions/1772
I suspect this will require a change in pythonnet.

**Comment by henon** [comment]
@longdrive01923 This issue is impossible to fix in C# without cooperation from the pythonnet guys. But there might be a way by writing a custom python function which we can then call. This custom function could forward the data to the np.gradient function.

**Comment by henon** [comment]
In any case, I opened another issue in pythonnet for this: https://github.com/pythonnet/pythonnet/issues/1804

**Comment by henon** [comment]
I fixed it. But the python version is now increased to 3.10 and the Numpy version is now 1.21.3

https://www.nuget.org/packages/Numpy/3.10.1.29

Usage of np.gradient:

```csharp

        [TestMethod]
        public void IssueByAllenP()
        {
            //>>> dx = 4.0
            //>>> dy = 5.0
            //>>> zX =[[1, 2, 3],[4,5,6],[8,9,0]]
            //>>> np.gradient(zX, dx, dy)
            //[array([[0.75, 0.75, 0.75],
            //       [0.875, 0.875, -0.375],
            //       [1.   , 1.   , -1.5]]), array([[0.2, 0.2, 0.2],
            //       [ 0.2,  0.2,  0.2],
            //       [ 0.2, -0.8, -1.8]])]
            var zX = new NDarray(new[,] { { 1, 2, 3 }, { 4, 5, 6 }, { 8, 9, 0 } });
            var result=np.gradient(zX, new List<double> { 4.0, 5.0 });
            var expected = @"[array([[ 0.75 ,  0.75 ,  0.75 ],
       [ 0.875,  0.875, -0.375],
       [ 1.   ,  1.   , -1.5  ]]), array([[ 0.2,  0.2,  0.2],
       [ 0.2,  0.2,  0.2],
       [ 0.2, -0.8, -1.8]])]".Replace("\r","");
            Assert.AreEqual(expected,result.repr);
        }
```
